/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _XDRBASETYPE_H_RPCGEN
#define _XDRBASETYPE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************
    苏州市轨道交通线网AFC技术规程

    Title       : xdrBaseType.x
    Version     : 2.0.1
    Author      : 宁哲
    Date        : 2010/11/8
    Description : 定义苏州轨道线网规程中的基础字段及系统常量
************************************************************************/
/************************************************************************

  evolution:
*************************************************************************
*    Date      *      Author           *     Changes
*************************************************************************
*   2010/01/07 *      宁哲             *     1.0.0 生成文档
*   2010/01/07 *      宁哲             *     1.0.1 完善文档内容
*   2010/01/14 *      宁哲             *     1.0.2 完善文档内容
*   2010/02/01 *      宁哲             *     1.0.3 增加对CPU储值票的相关支持
*   2010/03/10 *      宁哲             *     1.0.5 修改票卡物理编号的定义规则
*   2010/04/20 *      宁哲             *     1.0.6 使用ENUM定义枚举字段
*   2010/04/29 *      宁哲             *     1.0.7 增加一卡通相关记录 
*   2010/05/08 *      宁哲             *     1.0.8 所有票种的进出站交易记录，拆分为进站交易和出站交易
*                                                  所有票种的补票记录，按照补票原因进行拆分
*   2010/05/08 *      宁哲             *     1.0.10 调整退票、换票交易
*   2010/05/08 *      宁哲             *     1.0.12 增加LocalDateTime_t
*                                                       ePurseSN_t
*                                                       TransferStationID_t
*                                                       StaffGroupID_t
*   2010/09/17 *      宁哲             *     1.0.13 修改MD5的定义
*   2010/11/1  *      徐志君           *     2.0.0  TransactionType_t中增加班次暂停和班次恢复、电子钱包清零、苏州通锁卡、非指定区域区段出站等交易类型
*                                                   TransactionType_t中把TX_CPUCardMemberRegister_TX改成TX_CPUCardMemberRegister
*                                                   修改单程票TicketLogicalID_t使用规则同储值票
*                                                   去掉设备子类型DeviceSubType_t  
*   2010/11/18  *      诸仕荣           *     2.0.1  在“交易类型”（TransactionType_t）中增加“CPU票卡被拒绝”（TX_CPUCardReject）
*   2010/11/29  *      徐志君           *     2.0.1  在“交易类型”（TransactionType_t）中增加“BOM班次开始”（TX_ShiftStart）     
*   2011/03/23  *      诸仕荣           *     2.0.7  删除重复定义变量TicketQuantity_t  
*********************************************************************/
#ifndef XDR_BASETYPE_H
#define XDR_BASETYPE_H

#if defined(WIN32)
 #include <winsock.h>
 #include "d32-rpc.h"
#elif defined(VXWORKS)
 #include <rpc/rpc.h>
 #include "VxWorksCompliant.h"
#endif

#ifdef VXWORKS
 #define xdr_proc xdrproc_t
 #define WINAPI
#endif

#ifdef __cplusplus
extern "C" {
#endif
// ---------------------------------------------------------------------------------------
// ---- Definition of basic data type
// ---------------------------------------------------------------------------------------

typedef u_char U8_t;

typedef u_short U16_t;

typedef u_long U32_t;

typedef char S8_t;

typedef short S16_t;

typedef long S32_t;
// 布尔值

enum Boolean_t {
	FalseFlag = 0,
	TrueFlag = 1,
};
typedef enum Boolean_t Boolean_t;
// 金融单位：分
// 例如：1表示1分，10表示1角，100表示1元

typedef S32_t ValueCent_t;
// 段时间单位：毫秒

typedef U32_t MilliSecond_t;
// 段时间单位：秒

typedef U32_t Seconds_t;
// 据对时间单位：表示为据本地当日0点的描述，取值范围是0到86399
// 比如本地1:00AM可表示为3600；2:00AM可表示为7200

typedef U32_t SecondsSinceMidNight_t;
// UTC,通用协调时(UTC, Universal Time Coordinated)，表示格林威治时间。
// 此时间的取值与时区无关。各个操作系统都应有类似相同的方式来获取此时间。
// 0：表示格林威治1970年1月1日0分0秒
// 1：表示格林威治1970年1月1日0分1秒
// 转换成本地日期时间时，必须考虑北京时区8个小时的时差
// 在本系统中某任本地时间为北京时间，与操作系统的设置无关。
// Time_HI是预留的字段，对目前的系统设计作为预留字段使用
// Time_LO即UTC时间

struct SZAFCTime64_t {
	S32_t Time_HI;
	S32_t Time_LO;
};
typedef struct SZAFCTime64_t SZAFCTime64_t;
// 本地时间是指在格林威治时间的基础上，同时考虑地区时钟的差异。
// 例如北京为UTC+8:00时区。在计算本地时间时，各个操作系统都是可以设置本地时差的，所以各操作系统也提供了如何获取本地时间的方法。
// 但是由于ACC/AFC系统庞大，所涉及到的终端设备众多，为了强化系统时间同步，所有本地时间的获取需先取得UTC时间，
// 再计算北京时区差异的值，自行计算本地时间。
// 禁止直接获操作系统提供的本地时间。
// 这样做的好处可以使得所有设备共享时钟服务器，获得相同的本地时间。
// 而与本地时区设置的值无关。
// 0：1970年1月1日
// 1：1970年1月2日

typedef U16_t Date2_t;
// B31-B26：年(有效值为0到63；表示为2000年到2064年)
// B25-B22：月（有效值为1到12；表示为1月到12月；0、13、14、15为非法值）
// B21-B17：日（有效值为1到31；表示为1日到31日；0为非法值）
// B16-B12：时（有效值为0到23；表示为0点到23日；24到31为非法值）
// B11-B6：分（有效值为0到59；表示为0分到59分；60到63为非法值）
// B5-B0：秒（有效值为0到59；表示为0秒到59秒；60到63为非法值）
// 这样能表示64年，需要在全局参数中定义一个起始的基准年

typedef U32_t LocalDateTime_t;
// 
//
//
// ---------------------------------------------------------------------------------------
// ---- Transaction Message Type Definition
// ---------------------------------------------------------------------------------------
//	TX_CPUCardReplacement                   = 0x2D, /* 换票 */

enum TransactionType_t {
	TX_SJTSale = 0x01,
	TX_SJTOverstayingSurcharge = 0x02,
	TX_SJTUnderFareSurcharge = 0x03,
	TX_SJTNoExitSurcharge = 0x04,
	TX_SJTNoEntrySurcharge = 0x05,
	TX_SJTRefund = 0x06,
	TX_SJTEntry = 0x07,
	TX_SJTExit = 0x08,
	TX_CPUCardSale = 0x21,
	TX_CPUCardAddValue = 0x22,
	TX_CPUCardEntry = 0x23,
	TX_CPUCardExit = 0x24,
	TX_CPUCardOverstayingSurcharge = 0x25,
	TX_CPUCardUnderFareSurcharge = 0x26,
	TX_CPUCardNoExitSurcharge = 0x27,
	TX_CPUCardNoEntrySurcharge = 0x28,
	TX_CPUCardClearEntrySurcharge = 0x29,
	TX_CPUCardBlock = 0x2A,
	TX_CPUCardUnblock = 0x2B,
	TX_CPUCardDeduction = 0x2C,
	TX_CPUCardImmediateRefund = 0x2E,
	TX_CPUCardNonImmediateRefundRequest = 0x2F,
	TX_CPUCardNonImmediateRefundConfirm = 0x30,
	TX_CPUCardMemberRegister = 0x31,
	TX_CPUCardClearWallet = 0x32,
	TX_CPUCardReject = 0x33,
	TX_ShiftEnd = 0x60,
	TX_StockIn = 0x61,
	TX_StockOut = 0x62,
	TX_CoinBoxIn = 0x63,
	TX_CoinBoxOut = 0x64,
	TX_BankNoteBoxIn = 0x65,
	TX_BankNoteBoxOut = 0x66,
	TX_DrumBlockIn = 0x67,
	TX_DrumBlockOut = 0x68,
	TX_OperatorLogon = 0x69,
	TX_OperatorLogout = 0x6A,
	TX_HopperIn = 0x6B,
	TX_HopperOut = 0x6C,
	TX_ShiftBreak = 0x6D,
	TX_ShiftContinue = 0x6E,
	TX_ShiftStart = 0x6F,
	TX_YKTCardEntry = 0x90,
	TX_YKTCardExit = 0x91,
	TX_YKTCardOverstayingSurcharge = 0x92,
	TX_YKTCardUnderFareSurcharge = 0x93,
	TX_YKTCardNoExitSurcharge = 0x94,
	TX_YKTCardNoEntrySurcharge = 0x95,
	TX_YKTCardBlock = 0x96,
};
typedef enum TransactionType_t TransactionType_t;
// ---------------------------------------------------------------------------------------
// ---- EOD Type Definition
// ---------------------------------------------------------------------------------------

enum EODComponentType_t {
	EOD_CCHSSYSNetwork = 0x01,
	EOD_CCHSSYSCalendar = 0x02,
	EOD_CCHSSYSTicket = 0x03,
	EOD_CCHSSYSFare = 0x04,
	EOD_CCHSSYSTEM = 0x05,
	EOD_CCHSAGM = 0x06,
	EOD_CCHSTVM = 0x07,
	EOD_CCHSBOM = 0x08,
	EOD_CCHSAVM = 0x09,
	EOD_LCCAGM = 0x31,
	EOD_LCCTVM = 0x32,
	EOD_LCCBOM = 0x33,
	EOD_LCCAVM = 0x34,
	EOD_LCCSYSTEM = 0x35,
};
typedef enum EODComponentType_t EODComponentType_t;
// ---------------------------------------------------------------------------------------
// ---- 黑名单类型定义
// ---------------------------------------------------------------------------------------

enum BLKComponentType_t {
	BLK_YKT_FULL = 0x01,
	BLK_YKT_INCR = 0x02,
	BLK_CCHS_FULL = 0x03,
	BLK_CCHS_INCR = 0x04,
};
typedef enum BLKComponentType_t BLKComponentType_t;
// ---------------------------------------------------------------------------------------
// ---- Device generated files defintion
// ---------------------------------------------------------------------------------------

enum FileHeaderTag_t {
	FILE_HEADER_SJT_TRANSACTION = 0x01,
	FILE_HEADER_SV_TRANSACTION = 0x02,
	FILE_HEADER_YKT_TRANSACTION = 0x03,
	FILE_HEADER_FINANCE = 0x04,
	FILE_HEADER_AUDIT_REGISTER = 0x05,
	FILE_HEADER_EVENT = 0x06,
	FILE_HEADER_SV2_TRANSACTION = 0x07,
};
typedef enum FileHeaderTag_t FileHeaderTag_t;
// ---------------------------------------------------------------------------------------
// ---- CCHS Spec of public field
// ---------------------------------------------------------------------------------------

enum DeviceType_t {
	DEVICETYPE_CCHS = 0x01,
	DEVICETYPE_LCC = 0x02,
	DEVICETYPE_SC = 0x03,
	DEVICETYPE_AGM = 0x04,
	DEVICETYPE_AVM = 0x05,
	DEVICETYPE_TVM = 0x06,
	DEVICETYPE_BOM = 0x07,
	DEVICETYPE_PCA = 0x08,
	DEVICETYPE_ES = 0x09,
};
typedef enum DeviceType_t DeviceType_t;

enum ChipType_t {
	ULTRALIGHT = 0x01,
	METROCPUCARD = 0x02,
	YKTCPUCARD = 0x03,
};
typedef enum ChipType_t ChipType_t;
// 文件类别
// typedef U8_t               FileHeaderTag_t;
// 交易类别
// typedef U8_t               TransactionType_t;
// 测试标志位 0: 非测试票；1：测试票

typedef U8_t TestFlag_t;
// 线路编号

typedef U8_t LineID_t;
// 车站编号
// 高字节U8表示LineID_t，低字节字节表示为本线路的车站编号

typedef U16_t StationID_t;
// 线路内车站序列号
// typedef U8_t               StationIndex_t;
// 设备编号ID，4个字节，从高位低位分别表示
// 线路（U8_t）、车站（U8_t）、设备类型（U8_t）、设备在车站内的编号（U8_t）
// 

typedef U32_t DeviceID_t;
// SAM卡编号，4个字节
// U32_t从高位到低位分别表示SAMID[0]到SAMID[3]

typedef U32_t SAMID_t;
// 操作员编号
// 100000 - 999999

typedef U32_t OperatorID_t;
// BOM班次号

typedef U32_t BOMShiftID_t;
// 票卡类型(逻辑类型)

typedef U8_t TicketType_t;
// 票卡芯片类型（物理类型）
// 1: Mifare 1K
// 2: Mifare 4K
// 3: Ultraligth
// typedef U8_t               ChipType_t;
// UL票记录票卡使用的次数
// CPU卡记录票卡使用序列号，即地铁复合消费文件之TransactionTimes

typedef U32_t TicketSN_t;
// UL票无此信息，可填写0
// CPU卡记录票卡电子钱包脱机交易序列号

typedef U16_t ePurseSN_t;
// 设备交易序列号、文件序列号

typedef U32_t SN_t;
// 车站模式代码信息

typedef U8_t ModeCode_t;
// 定义车站的规模级别，客流报警、库存级别等信息均按照此级别来定义

typedef U8_t StationLevel_t;
// 区域编号

typedef U8_t ZoneID_t;
// 区域类别
// typedef U8_t            ZoneTypeID_t;
// 乘客类别编号

typedef U8_t PassengerTypeID_t;
// 区段编号

typedef U16_t SectionID_t;
// 区段类别

typedef U8_t SectionTypeID_t;
// 换乘车站编号

typedef U8_t TransferStationID_t;

typedef U8_t StaffGroupID_t;
// 票种大类类别
// 1: 一票通/单程票
// 2: 一票通/出站票
// 3: 一票通/计程票
// 4: 一票通/计次票
// 5: 一票通/月票
// 6: 一票通/员工票
// 7: 一卡通

typedef U8_t TicketFamily_t;
// 车票使用范围限制标志
// 0: 无使用范围限制
// 1: 在限定的区域使用
// 2: 在限定的区段使用

typedef U8_t AreaTicketFlag_t;
// AGM提示音

typedef U8_t SoundDisplayID_t;

typedef U8_t ConcessionalLampID_t;
// TAC值. 从U32的高位到低位分别表示为TAC的第1到第4个字节

typedef U32_t TAC_t;
// 票卡数量

typedef U32_t TicketQuantity_t;
// 单程票回收标志位：0:非回收类单程票；1:回收类单程票

typedef U8_t RecycleSJTFlag_t;
// 票箱编号              （票箱外部印刷号，注意：4个字节可能不足以填写电子标签号）

typedef U32_t ContainerID_t;
// 硬币钱箱编号          （硬币钱箱外部印刷号，注意：4个字节可能不足以填写电子标签号）

typedef U32_t CoinBoxID_t;
// 纸币钱箱编号          （纸币钱箱外部印刷号，注意：4个字节可能不足以填写电子标签号）

typedef U32_t BankNoteBoxID_t;
// 循环找零钱箱编号      （循环找零钱箱外部印刷号，注意：4个字节可能不足以填写电子标签号）

typedef U32_t DrumBlockID_t;
// 备用找零钱箱编号      （备用找零钱箱外部印刷号，注意：4个字节可能不足以填写电子标签号）

typedef U32_t HopperID_t;
// 硬币的个数，与硬币面额无关

typedef U32_t CoinQuantity_t;
// 纸币的张数，与纸币面额无关

typedef U32_t BanknoteQuantity_t;
// 计次票的乘车次数类别

typedef U8_t MultiRideTypeID_t;
// 计次票的乘车次数

typedef U32_t MultiRideNumber_t;
// 里程等级

typedef U8_t FareTier_t;
// 有效期类别
// 0: 对有效期不做检查；
// 1: 从第一次消费使用后（票卡DateOfCardFirstTransaction）的一段可配置时间内（票卡的Duration）有效；同时判断（票卡CSCEndDate，根据EOD的FixedEndDate获取）
// 2: 固定的起始时间A；POST当前的售票时间IssueDate的一段可配置时间内（EOD的Duration）有效；POST销售时写入票卡CSCStartDate和CSCEndDate
// 3: 以销售/充值后的一段时间有效；POST销售、充值(票卡LastAddingValueDate)后的一段可配置时间内（EOD的Duration）有效；仅限于车票有效期使用。在POST销售，写入CSCStartDate和CSCEndDate,在POST充值时，更新CSCEndDate
// 4: 固定的起始时间B；POST当前的售票时间IssueDate到某一个可配置时间点结束（EOD的FixedEndDate）；

typedef U8_t DurationMode_t;
// 有效期，单位：天

typedef U16_t Duration_t;
// 罚款类别

typedef U8_t RejectCode_t;
// 单据序列号

typedef U32_t ReceiptNumber_t;
// 锁卡原因代码

typedef U8_t BlockReasonCode_t;
// 频率，每分钟

typedef U32_t FrequencyWithinMin_t;
// 其他颜色再继续加

enum LampColorTypeID_t {
	lRED = 0,
	lYELLOW = 1,
	lGREEN = 2,
};
typedef enum LampColorTypeID_t LampColorTypeID_t;

enum ConcessionType_t {
	lNoConcession = 0,
	lBus2Metro = 1,
};
typedef enum ConcessionType_t ConcessionType_t;
// 日期类型
// 0：WKD
// 1：SAT
// 2：SUN
// 3：SPE

typedef U8_t DateTypeID_t;
// 费率类型代码

typedef U8_t TicketFareTypeID_t;
// 时间段编号

typedef U8_t TimeIntervalID_t;
// 车票费率组代码

typedef U8_t FareGroupID_t;
// 运营商编号

typedef U8_t SP_t;
// 数组长度

typedef U8_t ArraySize_t;
// 交易个数

typedef U32_t TransactionNb_t;
// 显示器坐标

typedef U32_t CoordinateUnit_t;
// 快速购票按钮编号

typedef U8_t ExpressBtnIndex_t;
// 线路/区域选择按钮编号

typedef U8_t LineZoneSelBtnID_t;
// 多媒体文件类别
// typedef U8_t               MultiMediaType_t;
// 票卡封面类型

typedef U8_t MediaType_t;
// 广告文件编号

typedef U8_t ADItemID_t;
// 多媒体文件类别
// 0: Flash; 

typedef U8_t MultiMediaType_t;
// TCP Port

typedef U16_t TCPPort_t;
// 模式履历版本号

typedef U32_t WaiverDateVersionID_t;
// 操作员组编号

typedef U32_t OperatorGroupID_t;
// 系统功能列表（包括线路、车站、及终端设备，具体定义待定）

typedef U32_t EQPFuncID_t;
// ID of Access Control Zone 

typedef U32_t ACZoneID_t;
// 摄氏度

typedef U16_t Centidegree_t;
// 次数记录

typedef U16_t Times_t;
// 黑名单版本号

typedef U32_t BLKVersionID_t;
// 黑名单模块类别
// 0: 一卡通黑名单(全量)
// 1: 一卡通黑名单(增量)
// 2: 一票通黑名单(全量)
// 3: 一票通黑名单(增量)
//typedef U8_t               BLKComponentType_t;
// 黑名单增量类别
// 0: 新增黑名单
// 1: 过期黑名单 （如果票卡属于过期黑名单，则此票卡属于可被正常处理的票卡）

typedef U8_t IncrBlacklistType_t;
// 黑名单处理编号
// 1: 锁卡
// 2: 不允许进站
// 3: 允许进，不允许出

typedef U8_t BLKActionType_t;
// EOD版本编号

typedef U32_t EODVersionID_t;
// 单程票密钥版本号

typedef U32_t KeyVersionID_t;
// EOD模块类别编号
// typedef U8_t               EODComponentType_t;
// 英文字符

typedef U8_t ENChar_t;
// 中文字符

typedef U16_t CNChar_t;
// 百分比 取值范围0--100，表示为0%到100%

typedef U8_t Percentage_t;
// 寄存器文件关闭的条件
// 0: 定期;
// 1: 当前运营日结束
// 2: 当前年运营日开始
// 3: 设备/车站恢复通讯
// 4: 拔出备用找零钱箱;    
// 5: 插入备用找零钱箱;
// 6: 拔出循环找零钱箱;  
// 7: 插入循环找零钱箱;
// 8: 拔出硬币钱箱;
// 9: 插入硬币钱箱;
// 10: 拔出纸币钱箱;
// 11: 插入纸币钱箱;
// 12: 拔出票箱;   
// 13: 插入票箱;
// 14: BOM班次开始
// 15: BOM班次结束

typedef U32_t ARFileTag_t;
// 设备寄存器字段

typedef U32_t ARItem_t;
// 0: 现金支付; 1: 储值卡支付; 2: 银行卡支付

typedef U8_t Paymentmeans_t;
// 0：身份证
// 1：学生证
// 2：残疾人证
// 3：军官证
// 4：老人证
// 5：护照
// 6：入境证

typedef U8_t IdentificationType_t;
// 票卡物理编号
//TicketPhyID_t 共8个字节
//U64_t从高位到低位8个字节分别表示如下：
//1. 高位首字节: 票卡分类(ChipType_t)
//2. 如果票卡物理编号为7个字节，则：
//高位第二字节到最后一个字节（7个字节）表示为票卡高位到低位的7个字节。
//3. 如果票卡物理编号为4个字节，则：
//   1）高位起第2、3、4字节到全部填写0x00.
//   2）高位起第5、6、7、8字节到填写票卡高位到低位的4个字节。

struct TicketPhyID_t {
	U32_t TicketPhyID_t_LO;
	U32_t TicketPhyID_t_HI;
};
typedef struct TicketPhyID_t TicketPhyID_t;
// 一卡通用户卡应用序列号
// 一卡通文档中记录使用16个BCD码
// 其前8个BCD数字，拆分为4个字节的HEX打印码，分别对应YKTTicketAPPID_t_HO的高位到低位的4个字节
// 其后8个BCD数字，拆分为4个字节的HEX打印码，分别对应YKTTicketAPPID_t_IO的高位到低位的4个字节
// 例如户卡应用序列号为1122334455667788则对应为：
// YKTTicketAPPID_HI为0x11223344
// YKTTicketAPPID_LO为0x55667788

struct YKTTicketAPPID_t {
	U32_t YKTTicketAPPID_t_LO;
	U32_t YKTTicketAPPID_t_HI;
};
typedef struct YKTTicketAPPID_t YKTTicketAPPID_t;
// 票卡印刷号，目前只有一票通储值票需要票卡卡面印刷号
// 按照规范的定义，暂定为“储值票卡卡面印刷号：2位厂商编码+2位产品编码+6位日期+1位批次号+5位流水号；”
// 具体内容待定

struct TicketCoverPrintNumber_t {
	U8_t TicketCoverPrintNumber[32];
};
typedef struct TicketCoverPrintNumber_t TicketCoverPrintNumber_t;
// 进出站交易标志位
// 0：进站交易；1：出站交易

typedef U8_t EntryExitBit_t;
// 票卡逻辑卡号
//使用规则
//TicketLogicalID_HI-从高位到低位依次为：前导码(U8_t)+卡印刷类型(U8_t)+批次日期(Date2_t)
//TicketLogicalID_LO-从高位到低位依次为：批次号(U8_t)+批次流水号(U16_t)+校验码(U8_t)
//其中单程票前导码1，储值票前导码6
//校验码前15位异或，异或后按10取模

struct TicketLogicalID_t {
	U32_t TicketLogicalID_HI;
	U32_t TicketLogicalID_LO;
};
typedef struct TicketLogicalID_t TicketLogicalID_t;
// MD5码一共16个字节，表示为MD5[0]到MD5[15]
// 在XDR文件中，使用4个的方式来定义
// MD5Tag[0]的4个字节从高位到低位分表为：存放MD5[0]、MD5[1]、MD5[2]、MD5[3]
// MD5Tag[1]的4个字节从高位到低位分表为：存放MD5[4]、MD5[5]、MD5[6]、MD5[7]
// MD5Tag[2]的4个字节从高位到低位分表为：存放MD5[8]、MD5[9]、MD5[10]、MD5[11]
// MD5Tag[3]的4个字节从高位到低位分表为：存放MD5[12]、MD5[13]、MD5[14]、MD5[15]
// 文件格式为【[原文]+16个字节的MD5】

struct MD5_t {
	U32_t MD5Tag[4];
};
typedef struct MD5_t MD5_t;
// ---------------------------------------------------------------------------------------
// ---- 库存文件类型
// ---------------------------------------------------------------------------------------

enum StockFileType_t {
	TICKET_STOCK_CLASS = 0x01,
	ENDOFDAY_STOCK_SANPSHOT = 0x02,
	STOCK_INOUT_BILL = 0x03,
	ENDOFDAY_STOCK_DIFF = 0x04,
	ENDOFDAY_PREPAYTICKET_SALESTAT = 0x05,
};
typedef enum StockFileType_t StockFileType_t;

typedef U16_t TicketDirClassID_t;

typedef U16_t TicketCatalogID_t;

typedef U8_t InOutType_t;

typedef U8_t InOutFlag_t;

typedef U32_t BatchNumber_t;
#ifdef __cplusplus
}
#endif

#endif

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_U8_t (XDR *, U8_t*);
extern  bool_t xdr_U16_t (XDR *, U16_t*);
extern  bool_t xdr_U32_t (XDR *, U32_t*);
extern  bool_t xdr_S8_t (XDR *, S8_t*);
extern  bool_t xdr_S16_t (XDR *, S16_t*);
extern  bool_t xdr_S32_t (XDR *, S32_t*);
extern  bool_t xdr_Boolean_t (XDR *, Boolean_t*);
extern  bool_t xdr_ValueCent_t (XDR *, ValueCent_t*);
extern  bool_t xdr_MilliSecond_t (XDR *, MilliSecond_t*);
extern  bool_t xdr_Seconds_t (XDR *, Seconds_t*);
extern  bool_t xdr_SecondsSinceMidNight_t (XDR *, SecondsSinceMidNight_t*);
extern  bool_t xdr_SZAFCTime64_t (XDR *, SZAFCTime64_t*);
extern  bool_t xdr_Date2_t (XDR *, Date2_t*);
extern  bool_t xdr_LocalDateTime_t (XDR *, LocalDateTime_t*);
extern  bool_t xdr_TransactionType_t (XDR *, TransactionType_t*);
extern  bool_t xdr_EODComponentType_t (XDR *, EODComponentType_t*);
extern  bool_t xdr_BLKComponentType_t (XDR *, BLKComponentType_t*);
extern  bool_t xdr_FileHeaderTag_t (XDR *, FileHeaderTag_t*);
extern  bool_t xdr_DeviceType_t (XDR *, DeviceType_t*);
extern  bool_t xdr_ChipType_t (XDR *, ChipType_t*);
extern  bool_t xdr_TestFlag_t (XDR *, TestFlag_t*);
extern  bool_t xdr_LineID_t (XDR *, LineID_t*);
extern  bool_t xdr_StationID_t (XDR *, StationID_t*);
extern  bool_t xdr_DeviceID_t (XDR *, DeviceID_t*);
extern  bool_t xdr_SAMID_t (XDR *, SAMID_t*);
extern  bool_t xdr_OperatorID_t (XDR *, OperatorID_t*);
extern  bool_t xdr_BOMShiftID_t (XDR *, BOMShiftID_t*);
extern  bool_t xdr_TicketType_t (XDR *, TicketType_t*);
extern  bool_t xdr_TicketSN_t (XDR *, TicketSN_t*);
extern  bool_t xdr_ePurseSN_t (XDR *, ePurseSN_t*);
extern  bool_t xdr_SN_t (XDR *, SN_t*);
extern  bool_t xdr_ModeCode_t (XDR *, ModeCode_t*);
extern  bool_t xdr_StationLevel_t (XDR *, StationLevel_t*);
extern  bool_t xdr_ZoneID_t (XDR *, ZoneID_t*);
extern  bool_t xdr_PassengerTypeID_t (XDR *, PassengerTypeID_t*);
extern  bool_t xdr_SectionID_t (XDR *, SectionID_t*);
extern  bool_t xdr_SectionTypeID_t (XDR *, SectionTypeID_t*);
extern  bool_t xdr_TransferStationID_t (XDR *, TransferStationID_t*);
extern  bool_t xdr_StaffGroupID_t (XDR *, StaffGroupID_t*);
extern  bool_t xdr_TicketFamily_t (XDR *, TicketFamily_t*);
extern  bool_t xdr_AreaTicketFlag_t (XDR *, AreaTicketFlag_t*);
extern  bool_t xdr_SoundDisplayID_t (XDR *, SoundDisplayID_t*);
extern  bool_t xdr_ConcessionalLampID_t (XDR *, ConcessionalLampID_t*);
extern  bool_t xdr_TAC_t (XDR *, TAC_t*);
extern  bool_t xdr_TicketQuantity_t (XDR *, TicketQuantity_t*);
extern  bool_t xdr_RecycleSJTFlag_t (XDR *, RecycleSJTFlag_t*);
extern  bool_t xdr_ContainerID_t (XDR *, ContainerID_t*);
extern  bool_t xdr_CoinBoxID_t (XDR *, CoinBoxID_t*);
extern  bool_t xdr_BankNoteBoxID_t (XDR *, BankNoteBoxID_t*);
extern  bool_t xdr_DrumBlockID_t (XDR *, DrumBlockID_t*);
extern  bool_t xdr_HopperID_t (XDR *, HopperID_t*);
extern  bool_t xdr_CoinQuantity_t (XDR *, CoinQuantity_t*);
extern  bool_t xdr_BanknoteQuantity_t (XDR *, BanknoteQuantity_t*);
extern  bool_t xdr_MultiRideTypeID_t (XDR *, MultiRideTypeID_t*);
extern  bool_t xdr_MultiRideNumber_t (XDR *, MultiRideNumber_t*);
extern  bool_t xdr_FareTier_t (XDR *, FareTier_t*);
extern  bool_t xdr_DurationMode_t (XDR *, DurationMode_t*);
extern  bool_t xdr_Duration_t (XDR *, Duration_t*);
extern  bool_t xdr_RejectCode_t (XDR *, RejectCode_t*);
extern  bool_t xdr_ReceiptNumber_t (XDR *, ReceiptNumber_t*);
extern  bool_t xdr_BlockReasonCode_t (XDR *, BlockReasonCode_t*);
extern  bool_t xdr_FrequencyWithinMin_t (XDR *, FrequencyWithinMin_t*);
extern  bool_t xdr_LampColorTypeID_t (XDR *, LampColorTypeID_t*);
extern  bool_t xdr_ConcessionType_t (XDR *, ConcessionType_t*);
extern  bool_t xdr_DateTypeID_t (XDR *, DateTypeID_t*);
extern  bool_t xdr_TicketFareTypeID_t (XDR *, TicketFareTypeID_t*);
extern  bool_t xdr_TimeIntervalID_t (XDR *, TimeIntervalID_t*);
extern  bool_t xdr_FareGroupID_t (XDR *, FareGroupID_t*);
extern  bool_t xdr_SP_t (XDR *, SP_t*);
extern  bool_t xdr_ArraySize_t (XDR *, ArraySize_t*);
extern  bool_t xdr_TransactionNb_t (XDR *, TransactionNb_t*);
extern  bool_t xdr_CoordinateUnit_t (XDR *, CoordinateUnit_t*);
extern  bool_t xdr_ExpressBtnIndex_t (XDR *, ExpressBtnIndex_t*);
extern  bool_t xdr_LineZoneSelBtnID_t (XDR *, LineZoneSelBtnID_t*);
extern  bool_t xdr_MediaType_t (XDR *, MediaType_t*);
extern  bool_t xdr_ADItemID_t (XDR *, ADItemID_t*);
extern  bool_t xdr_MultiMediaType_t (XDR *, MultiMediaType_t*);
extern  bool_t xdr_TCPPort_t (XDR *, TCPPort_t*);
extern  bool_t xdr_WaiverDateVersionID_t (XDR *, WaiverDateVersionID_t*);
extern  bool_t xdr_OperatorGroupID_t (XDR *, OperatorGroupID_t*);
extern  bool_t xdr_EQPFuncID_t (XDR *, EQPFuncID_t*);
extern  bool_t xdr_ACZoneID_t (XDR *, ACZoneID_t*);
extern  bool_t xdr_Centidegree_t (XDR *, Centidegree_t*);
extern  bool_t xdr_Times_t (XDR *, Times_t*);
extern  bool_t xdr_BLKVersionID_t (XDR *, BLKVersionID_t*);
extern  bool_t xdr_IncrBlacklistType_t (XDR *, IncrBlacklistType_t*);
extern  bool_t xdr_BLKActionType_t (XDR *, BLKActionType_t*);
extern  bool_t xdr_EODVersionID_t (XDR *, EODVersionID_t*);
extern  bool_t xdr_KeyVersionID_t (XDR *, KeyVersionID_t*);
extern  bool_t xdr_ENChar_t (XDR *, ENChar_t*);
extern  bool_t xdr_CNChar_t (XDR *, CNChar_t*);
extern  bool_t xdr_Percentage_t (XDR *, Percentage_t*);
extern  bool_t xdr_ARFileTag_t (XDR *, ARFileTag_t*);
extern  bool_t xdr_ARItem_t (XDR *, ARItem_t*);
extern  bool_t xdr_Paymentmeans_t (XDR *, Paymentmeans_t*);
extern  bool_t xdr_IdentificationType_t (XDR *, IdentificationType_t*);
extern  bool_t xdr_TicketPhyID_t (XDR *, TicketPhyID_t*);
extern  bool_t xdr_YKTTicketAPPID_t (XDR *, YKTTicketAPPID_t*);
extern  bool_t xdr_TicketCoverPrintNumber_t (XDR *, TicketCoverPrintNumber_t*);
extern  bool_t xdr_EntryExitBit_t (XDR *, EntryExitBit_t*);
extern  bool_t xdr_TicketLogicalID_t (XDR *, TicketLogicalID_t*);
extern  bool_t xdr_MD5_t (XDR *, MD5_t*);
extern  bool_t xdr_StockFileType_t (XDR *, StockFileType_t*);
extern  bool_t xdr_TicketDirClassID_t (XDR *, TicketDirClassID_t*);
extern  bool_t xdr_TicketCatalogID_t (XDR *, TicketCatalogID_t*);
extern  bool_t xdr_InOutType_t (XDR *, InOutType_t*);
extern  bool_t xdr_InOutFlag_t (XDR *, InOutFlag_t*);
extern  bool_t xdr_BatchNumber_t (XDR *, BatchNumber_t*);

#else /* K&R C */
extern bool_t xdr_U8_t ();
extern bool_t xdr_U16_t ();
extern bool_t xdr_U32_t ();
extern bool_t xdr_S8_t ();
extern bool_t xdr_S16_t ();
extern bool_t xdr_S32_t ();
extern bool_t xdr_Boolean_t ();
extern bool_t xdr_ValueCent_t ();
extern bool_t xdr_MilliSecond_t ();
extern bool_t xdr_Seconds_t ();
extern bool_t xdr_SecondsSinceMidNight_t ();
extern bool_t xdr_SZAFCTime64_t ();
extern bool_t xdr_Date2_t ();
extern bool_t xdr_LocalDateTime_t ();
extern bool_t xdr_TransactionType_t ();
extern bool_t xdr_EODComponentType_t ();
extern bool_t xdr_BLKComponentType_t ();
extern bool_t xdr_FileHeaderTag_t ();
extern bool_t xdr_DeviceType_t ();
extern bool_t xdr_ChipType_t ();
extern bool_t xdr_TestFlag_t ();
extern bool_t xdr_LineID_t ();
extern bool_t xdr_StationID_t ();
extern bool_t xdr_DeviceID_t ();
extern bool_t xdr_SAMID_t ();
extern bool_t xdr_OperatorID_t ();
extern bool_t xdr_BOMShiftID_t ();
extern bool_t xdr_TicketType_t ();
extern bool_t xdr_TicketSN_t ();
extern bool_t xdr_ePurseSN_t ();
extern bool_t xdr_SN_t ();
extern bool_t xdr_ModeCode_t ();
extern bool_t xdr_StationLevel_t ();
extern bool_t xdr_ZoneID_t ();
extern bool_t xdr_PassengerTypeID_t ();
extern bool_t xdr_SectionID_t ();
extern bool_t xdr_SectionTypeID_t ();
extern bool_t xdr_TransferStationID_t ();
extern bool_t xdr_StaffGroupID_t ();
extern bool_t xdr_TicketFamily_t ();
extern bool_t xdr_AreaTicketFlag_t ();
extern bool_t xdr_SoundDisplayID_t ();
extern bool_t xdr_ConcessionalLampID_t ();
extern bool_t xdr_TAC_t ();
extern bool_t xdr_TicketQuantity_t ();
extern bool_t xdr_RecycleSJTFlag_t ();
extern bool_t xdr_ContainerID_t ();
extern bool_t xdr_CoinBoxID_t ();
extern bool_t xdr_BankNoteBoxID_t ();
extern bool_t xdr_DrumBlockID_t ();
extern bool_t xdr_HopperID_t ();
extern bool_t xdr_CoinQuantity_t ();
extern bool_t xdr_BanknoteQuantity_t ();
extern bool_t xdr_MultiRideTypeID_t ();
extern bool_t xdr_MultiRideNumber_t ();
extern bool_t xdr_FareTier_t ();
extern bool_t xdr_DurationMode_t ();
extern bool_t xdr_Duration_t ();
extern bool_t xdr_RejectCode_t ();
extern bool_t xdr_ReceiptNumber_t ();
extern bool_t xdr_BlockReasonCode_t ();
extern bool_t xdr_FrequencyWithinMin_t ();
extern bool_t xdr_LampColorTypeID_t ();
extern bool_t xdr_ConcessionType_t ();
extern bool_t xdr_DateTypeID_t ();
extern bool_t xdr_TicketFareTypeID_t ();
extern bool_t xdr_TimeIntervalID_t ();
extern bool_t xdr_FareGroupID_t ();
extern bool_t xdr_SP_t ();
extern bool_t xdr_ArraySize_t ();
extern bool_t xdr_TransactionNb_t ();
extern bool_t xdr_CoordinateUnit_t ();
extern bool_t xdr_ExpressBtnIndex_t ();
extern bool_t xdr_LineZoneSelBtnID_t ();
extern bool_t xdr_MediaType_t ();
extern bool_t xdr_ADItemID_t ();
extern bool_t xdr_MultiMediaType_t ();
extern bool_t xdr_TCPPort_t ();
extern bool_t xdr_WaiverDateVersionID_t ();
extern bool_t xdr_OperatorGroupID_t ();
extern bool_t xdr_EQPFuncID_t ();
extern bool_t xdr_ACZoneID_t ();
extern bool_t xdr_Centidegree_t ();
extern bool_t xdr_Times_t ();
extern bool_t xdr_BLKVersionID_t ();
extern bool_t xdr_IncrBlacklistType_t ();
extern bool_t xdr_BLKActionType_t ();
extern bool_t xdr_EODVersionID_t ();
extern bool_t xdr_KeyVersionID_t ();
extern bool_t xdr_ENChar_t ();
extern bool_t xdr_CNChar_t ();
extern bool_t xdr_Percentage_t ();
extern bool_t xdr_ARFileTag_t ();
extern bool_t xdr_ARItem_t ();
extern bool_t xdr_Paymentmeans_t ();
extern bool_t xdr_IdentificationType_t ();
extern bool_t xdr_TicketPhyID_t ();
extern bool_t xdr_YKTTicketAPPID_t ();
extern bool_t xdr_TicketCoverPrintNumber_t ();
extern bool_t xdr_EntryExitBit_t ();
extern bool_t xdr_TicketLogicalID_t ();
extern bool_t xdr_MD5_t ();
extern bool_t xdr_StockFileType_t ();
extern bool_t xdr_TicketDirClassID_t ();
extern bool_t xdr_TicketCatalogID_t ();
extern bool_t xdr_InOutType_t ();
extern bool_t xdr_InOutFlag_t ();
extern bool_t xdr_BatchNumber_t ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_XDRBASETYPE_H_RPCGEN */
