/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "xdrBaseType.h"
/**********************************************************************
    苏州市轨道交通线网AFC技术规程

    Title       : xdrBaseType.x
    Version     : 2.0.1
    Author      : 宁哲
    Date        : 2010/11/8
    Description : 定义苏州轨道线网规程中的基础字段及系统常量
************************************************************************/
/************************************************************************

  evolution:
*************************************************************************
*    Date      *      Author           *     Changes
*************************************************************************
*   2010/01/07 *      宁哲             *     1.0.0 生成文档
*   2010/01/07 *      宁哲             *     1.0.1 完善文档内容
*   2010/01/14 *      宁哲             *     1.0.2 完善文档内容
*   2010/02/01 *      宁哲             *     1.0.3 增加对CPU储值票的相关支持
*   2010/03/10 *      宁哲             *     1.0.5 修改票卡物理编号的定义规则
*   2010/04/20 *      宁哲             *     1.0.6 使用ENUM定义枚举字段
*   2010/04/29 *      宁哲             *     1.0.7 增加一卡通相关记录 
*   2010/05/08 *      宁哲             *     1.0.8 所有票种的进出站交易记录，拆分为进站交易和出站交易
*                                                  所有票种的补票记录，按照补票原因进行拆分
*   2010/05/08 *      宁哲             *     1.0.10 调整退票、换票交易
*   2010/05/08 *      宁哲             *     1.0.12 增加LocalDateTime_t
*                                                       ePurseSN_t
*                                                       TransferStationID_t
*                                                       StaffGroupID_t
*   2010/09/17 *      宁哲             *     1.0.13 修改MD5的定义
*   2010/11/1  *      徐志君           *     2.0.0  TransactionType_t中增加班次暂停和班次恢复、电子钱包清零、苏州通锁卡、非指定区域区段出站等交易类型
*                                                   TransactionType_t中把TX_CPUCardMemberRegister_TX改成TX_CPUCardMemberRegister
*                                                   修改单程票TicketLogicalID_t使用规则同储值票
*                                                   去掉设备子类型DeviceSubType_t  
*   2010/11/18  *      诸仕荣           *     2.0.1  在“交易类型”（TransactionType_t）中增加“CPU票卡被拒绝”（TX_CPUCardReject）
*   2010/11/29  *      徐志君           *     2.0.1  在“交易类型”（TransactionType_t）中增加“BOM班次开始”（TX_ShiftStart）     
*   2011/03/23  *      诸仕荣           *     2.0.7  删除重复定义变量TicketQuantity_t  
*********************************************************************/
//#ifndef XDR_BASETYPE_H
//#define XDR_BASETYPE_H

#if defined(WIN32)
 #include <winsock.h>
 #include "d32-rpc.h"
#elif defined(VXWORKS)
 #include <rpc/rpc.h>
 #include "VxWorksCompliant.h"
#endif

#ifdef VXWORKS
 #define xdr_proc xdrproc_t
 #define WINAPI
#endif

#ifdef __cplusplus
extern "C" {
#endif
// ---------------------------------------------------------------------------------------
// ---- Definition of basic data type
// ---------------------------------------------------------------------------------------

bool_t
xdr_U8_t (XDR *xdrs, U8_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_char (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_U16_t (XDR *xdrs, U16_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_short (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_U32_t (XDR *xdrs, U32_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_S8_t (XDR *xdrs, S8_t *objp)
{
	register int32_t *buf;

	 if (!xdr_char (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_S16_t (XDR *xdrs, S16_t *objp)
{
	register int32_t *buf;

	 if (!xdr_short (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_S32_t (XDR *xdrs, S32_t *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 布尔值

bool_t
xdr_Boolean_t (XDR *xdrs, Boolean_t *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}
// 金融单位：分
// 例如：1表示1分，10表示1角，100表示1元

bool_t
xdr_ValueCent_t (XDR *xdrs, ValueCent_t *objp)
{
	register int32_t *buf;

	 if (!xdr_S32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 段时间单位：毫秒

bool_t
xdr_MilliSecond_t (XDR *xdrs, MilliSecond_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 段时间单位：秒

bool_t
xdr_Seconds_t (XDR *xdrs, Seconds_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 据对时间单位：表示为据本地当日0点的描述，取值范围是0到86399
// 比如本地1:00AM可表示为3600；2:00AM可表示为7200

bool_t
xdr_SecondsSinceMidNight_t (XDR *xdrs, SecondsSinceMidNight_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// UTC,通用协调时(UTC, Universal Time Coordinated)，表示格林威治时间。
// 此时间的取值与时区无关。各个操作系统都应有类似相同的方式来获取此时间。
// 0：表示格林威治1970年1月1日0分0秒
// 1：表示格林威治1970年1月1日0分1秒
// 转换成本地日期时间时，必须考虑北京时区8个小时的时差
// 在本系统中某任本地时间为北京时间，与操作系统的设置无关。
// Time_HI是预留的字段，对目前的系统设计作为预留字段使用
// Time_LO即UTC时间

bool_t
xdr_SZAFCTime64_t (XDR *xdrs, SZAFCTime64_t *objp)
{
	register int32_t *buf;

	 if (!xdr_S32_t (xdrs, &objp->Time_HI))
		 return FALSE;
	 if (!xdr_S32_t (xdrs, &objp->Time_LO))
		 return FALSE;
	return TRUE;
}
// 本地时间是指在格林威治时间的基础上，同时考虑地区时钟的差异。
// 例如北京为UTC+8:00时区。在计算本地时间时，各个操作系统都是可以设置本地时差的，所以各操作系统也提供了如何获取本地时间的方法。
// 但是由于ACC/AFC系统庞大，所涉及到的终端设备众多，为了强化系统时间同步，所有本地时间的获取需先取得UTC时间，
// 再计算北京时区差异的值，自行计算本地时间。
// 禁止直接获操作系统提供的本地时间。
// 这样做的好处可以使得所有设备共享时钟服务器，获得相同的本地时间。
// 而与本地时区设置的值无关。
// 0：1970年1月1日
// 1：1970年1月2日

bool_t
xdr_Date2_t (XDR *xdrs, Date2_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U16_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// B31-B26：年(有效值为0到63；表示为2000年到2064年)
// B25-B22：月（有效值为1到12；表示为1月到12月；0、13、14、15为非法值）
// B21-B17：日（有效值为1到31；表示为1日到31日；0为非法值）
// B16-B12：时（有效值为0到23；表示为0点到23日；24到31为非法值）
// B11-B6：分（有效值为0到59；表示为0分到59分；60到63为非法值）
// B5-B0：秒（有效值为0到59；表示为0秒到59秒；60到63为非法值）
// 这样能表示64年，需要在全局参数中定义一个起始的基准年

bool_t
xdr_LocalDateTime_t (XDR *xdrs, LocalDateTime_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 
//
//
// ---------------------------------------------------------------------------------------
// ---- Transaction Message Type Definition
// ---------------------------------------------------------------------------------------
//	TX_CPUCardReplacement                   = 0x2D, /* 换票 */

bool_t
xdr_TransactionType_t (XDR *xdrs, TransactionType_t *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}
// ---------------------------------------------------------------------------------------
// ---- EOD Type Definition
// ---------------------------------------------------------------------------------------

bool_t
xdr_EODComponentType_t (XDR *xdrs, EODComponentType_t *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}
// ---------------------------------------------------------------------------------------
// ---- 黑名单类型定义
// ---------------------------------------------------------------------------------------

bool_t
xdr_BLKComponentType_t (XDR *xdrs, BLKComponentType_t *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}
// ---------------------------------------------------------------------------------------
// ---- Device generated files defintion
// ---------------------------------------------------------------------------------------

bool_t
xdr_FileHeaderTag_t (XDR *xdrs, FileHeaderTag_t *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}
// ---------------------------------------------------------------------------------------
// ---- CCHS Spec of public field
// ---------------------------------------------------------------------------------------

bool_t
xdr_DeviceType_t (XDR *xdrs, DeviceType_t *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ChipType_t (XDR *xdrs, ChipType_t *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}
// 文件类别
// typedef U8_t               FileHeaderTag_t;
// 交易类别
// typedef U8_t               TransactionType_t;
// 测试标志位 0: 非测试票；1：测试票

bool_t
xdr_TestFlag_t (XDR *xdrs, TestFlag_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 线路编号

bool_t
xdr_LineID_t (XDR *xdrs, LineID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 车站编号
// 高字节U8表示LineID_t，低字节字节表示为本线路的车站编号

bool_t
xdr_StationID_t (XDR *xdrs, StationID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U16_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 线路内车站序列号
// typedef U8_t               StationIndex_t;
// 设备编号ID，4个字节，从高位低位分别表示
// 线路（U8_t）、车站（U8_t）、设备类型（U8_t）、设备在车站内的编号（U8_t）
// 

bool_t
xdr_DeviceID_t (XDR *xdrs, DeviceID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// SAM卡编号，4个字节
// U32_t从高位到低位分别表示SAMID[0]到SAMID[3]

bool_t
xdr_SAMID_t (XDR *xdrs, SAMID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 操作员编号
// 100000 - 999999

bool_t
xdr_OperatorID_t (XDR *xdrs, OperatorID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// BOM班次号

bool_t
xdr_BOMShiftID_t (XDR *xdrs, BOMShiftID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 票卡类型(逻辑类型)

bool_t
xdr_TicketType_t (XDR *xdrs, TicketType_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 票卡芯片类型（物理类型）
// 1: Mifare 1K
// 2: Mifare 4K
// 3: Ultraligth
// typedef U8_t               ChipType_t;
// UL票记录票卡使用的次数
// CPU卡记录票卡使用序列号，即地铁复合消费文件之TransactionTimes

bool_t
xdr_TicketSN_t (XDR *xdrs, TicketSN_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// UL票无此信息，可填写0
// CPU卡记录票卡电子钱包脱机交易序列号

bool_t
xdr_ePurseSN_t (XDR *xdrs, ePurseSN_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U16_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 设备交易序列号、文件序列号

bool_t
xdr_SN_t (XDR *xdrs, SN_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 车站模式代码信息

bool_t
xdr_ModeCode_t (XDR *xdrs, ModeCode_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 定义车站的规模级别，客流报警、库存级别等信息均按照此级别来定义

bool_t
xdr_StationLevel_t (XDR *xdrs, StationLevel_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 区域编号

bool_t
xdr_ZoneID_t (XDR *xdrs, ZoneID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 区域类别
// typedef U8_t            ZoneTypeID_t;
// 乘客类别编号

bool_t
xdr_PassengerTypeID_t (XDR *xdrs, PassengerTypeID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 区段编号

bool_t
xdr_SectionID_t (XDR *xdrs, SectionID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U16_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 区段类别

bool_t
xdr_SectionTypeID_t (XDR *xdrs, SectionTypeID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 换乘车站编号

bool_t
xdr_TransferStationID_t (XDR *xdrs, TransferStationID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_StaffGroupID_t (XDR *xdrs, StaffGroupID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 票种大类类别
// 1: 一票通/单程票
// 2: 一票通/出站票
// 3: 一票通/计程票
// 4: 一票通/计次票
// 5: 一票通/月票
// 6: 一票通/员工票
// 7: 一卡通

bool_t
xdr_TicketFamily_t (XDR *xdrs, TicketFamily_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 车票使用范围限制标志
// 0: 无使用范围限制
// 1: 在限定的区域使用
// 2: 在限定的区段使用

bool_t
xdr_AreaTicketFlag_t (XDR *xdrs, AreaTicketFlag_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// AGM提示音

bool_t
xdr_SoundDisplayID_t (XDR *xdrs, SoundDisplayID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ConcessionalLampID_t (XDR *xdrs, ConcessionalLampID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// TAC值. 从U32的高位到低位分别表示为TAC的第1到第4个字节

bool_t
xdr_TAC_t (XDR *xdrs, TAC_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 票卡数量

bool_t
xdr_TicketQuantity_t (XDR *xdrs, TicketQuantity_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 单程票回收标志位：0:非回收类单程票；1:回收类单程票

bool_t
xdr_RecycleSJTFlag_t (XDR *xdrs, RecycleSJTFlag_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 票箱编号              （票箱外部印刷号，注意：4个字节可能不足以填写电子标签号）

bool_t
xdr_ContainerID_t (XDR *xdrs, ContainerID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 硬币钱箱编号          （硬币钱箱外部印刷号，注意：4个字节可能不足以填写电子标签号）

bool_t
xdr_CoinBoxID_t (XDR *xdrs, CoinBoxID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 纸币钱箱编号          （纸币钱箱外部印刷号，注意：4个字节可能不足以填写电子标签号）

bool_t
xdr_BankNoteBoxID_t (XDR *xdrs, BankNoteBoxID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 循环找零钱箱编号      （循环找零钱箱外部印刷号，注意：4个字节可能不足以填写电子标签号）

bool_t
xdr_DrumBlockID_t (XDR *xdrs, DrumBlockID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 备用找零钱箱编号      （备用找零钱箱外部印刷号，注意：4个字节可能不足以填写电子标签号）

bool_t
xdr_HopperID_t (XDR *xdrs, HopperID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 硬币的个数，与硬币面额无关

bool_t
xdr_CoinQuantity_t (XDR *xdrs, CoinQuantity_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 纸币的张数，与纸币面额无关

bool_t
xdr_BanknoteQuantity_t (XDR *xdrs, BanknoteQuantity_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 计次票的乘车次数类别

bool_t
xdr_MultiRideTypeID_t (XDR *xdrs, MultiRideTypeID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 计次票的乘车次数

bool_t
xdr_MultiRideNumber_t (XDR *xdrs, MultiRideNumber_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 里程等级

bool_t
xdr_FareTier_t (XDR *xdrs, FareTier_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 有效期类别
// 0: 对有效期不做检查；
// 1: 从第一次消费使用后（票卡DateOfCardFirstTransaction）的一段可配置时间内（票卡的Duration）有效；同时判断（票卡CSCEndDate，根据EOD的FixedEndDate获取）
// 2: 固定的起始时间A；POST当前的售票时间IssueDate的一段可配置时间内（EOD的Duration）有效；POST销售时写入票卡CSCStartDate和CSCEndDate
// 3: 以销售/充值后的一段时间有效；POST销售、充值(票卡LastAddingValueDate)后的一段可配置时间内（EOD的Duration）有效；仅限于车票有效期使用。在POST销售，写入CSCStartDate和CSCEndDate,在POST充值时，更新CSCEndDate
// 4: 固定的起始时间B；POST当前的售票时间IssueDate到某一个可配置时间点结束（EOD的FixedEndDate）；

bool_t
xdr_DurationMode_t (XDR *xdrs, DurationMode_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 有效期，单位：天

bool_t
xdr_Duration_t (XDR *xdrs, Duration_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U16_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 罚款类别

bool_t
xdr_RejectCode_t (XDR *xdrs, RejectCode_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 单据序列号

bool_t
xdr_ReceiptNumber_t (XDR *xdrs, ReceiptNumber_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 锁卡原因代码

bool_t
xdr_BlockReasonCode_t (XDR *xdrs, BlockReasonCode_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 频率，每分钟

bool_t
xdr_FrequencyWithinMin_t (XDR *xdrs, FrequencyWithinMin_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 其他颜色再继续加

bool_t
xdr_LampColorTypeID_t (XDR *xdrs, LampColorTypeID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ConcessionType_t (XDR *xdrs, ConcessionType_t *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}
// 日期类型
// 0：WKD
// 1：SAT
// 2：SUN
// 3：SPE

bool_t
xdr_DateTypeID_t (XDR *xdrs, DateTypeID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 费率类型代码

bool_t
xdr_TicketFareTypeID_t (XDR *xdrs, TicketFareTypeID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 时间段编号

bool_t
xdr_TimeIntervalID_t (XDR *xdrs, TimeIntervalID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 车票费率组代码

bool_t
xdr_FareGroupID_t (XDR *xdrs, FareGroupID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 运营商编号

bool_t
xdr_SP_t (XDR *xdrs, SP_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 数组长度

bool_t
xdr_ArraySize_t (XDR *xdrs, ArraySize_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 交易个数

bool_t
xdr_TransactionNb_t (XDR *xdrs, TransactionNb_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 显示器坐标

bool_t
xdr_CoordinateUnit_t (XDR *xdrs, CoordinateUnit_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 快速购票按钮编号

bool_t
xdr_ExpressBtnIndex_t (XDR *xdrs, ExpressBtnIndex_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 线路/区域选择按钮编号

bool_t
xdr_LineZoneSelBtnID_t (XDR *xdrs, LineZoneSelBtnID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 多媒体文件类别
// typedef U8_t               MultiMediaType_t;
// 票卡封面类型

bool_t
xdr_MediaType_t (XDR *xdrs, MediaType_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 广告文件编号

bool_t
xdr_ADItemID_t (XDR *xdrs, ADItemID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 多媒体文件类别
// 0: Flash; 

bool_t
xdr_MultiMediaType_t (XDR *xdrs, MultiMediaType_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// TCP Port

bool_t
xdr_TCPPort_t (XDR *xdrs, TCPPort_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U16_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 模式履历版本号

bool_t
xdr_WaiverDateVersionID_t (XDR *xdrs, WaiverDateVersionID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 操作员组编号

bool_t
xdr_OperatorGroupID_t (XDR *xdrs, OperatorGroupID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 系统功能列表（包括线路、车站、及终端设备，具体定义待定）

bool_t
xdr_EQPFuncID_t (XDR *xdrs, EQPFuncID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// ID of Access Control Zone 

bool_t
xdr_ACZoneID_t (XDR *xdrs, ACZoneID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 摄氏度

bool_t
xdr_Centidegree_t (XDR *xdrs, Centidegree_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U16_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 次数记录

bool_t
xdr_Times_t (XDR *xdrs, Times_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U16_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 黑名单版本号

bool_t
xdr_BLKVersionID_t (XDR *xdrs, BLKVersionID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 黑名单模块类别
// 0: 一卡通黑名单(全量)
// 1: 一卡通黑名单(增量)
// 2: 一票通黑名单(全量)
// 3: 一票通黑名单(增量)
//typedef U8_t               BLKComponentType_t;
// 黑名单增量类别
// 0: 新增黑名单
// 1: 过期黑名单 （如果票卡属于过期黑名单，则此票卡属于可被正常处理的票卡）

bool_t
xdr_IncrBlacklistType_t (XDR *xdrs, IncrBlacklistType_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 黑名单处理编号
// 1: 锁卡
// 2: 不允许进站
// 3: 允许进，不允许出

bool_t
xdr_BLKActionType_t (XDR *xdrs, BLKActionType_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// EOD版本编号

bool_t
xdr_EODVersionID_t (XDR *xdrs, EODVersionID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 单程票密钥版本号

bool_t
xdr_KeyVersionID_t (XDR *xdrs, KeyVersionID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// EOD模块类别编号
// typedef U8_t               EODComponentType_t;
// 英文字符

bool_t
xdr_ENChar_t (XDR *xdrs, ENChar_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 中文字符

bool_t
xdr_CNChar_t (XDR *xdrs, CNChar_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U16_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 百分比 取值范围0--100，表示为0%到100%

bool_t
xdr_Percentage_t (XDR *xdrs, Percentage_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 寄存器文件关闭的条件
// 0: 定期;
// 1: 当前运营日结束
// 2: 当前年运营日开始
// 3: 设备/车站恢复通讯
// 4: 拔出备用找零钱箱;    
// 5: 插入备用找零钱箱;
// 6: 拔出循环找零钱箱;  
// 7: 插入循环找零钱箱;
// 8: 拔出硬币钱箱;
// 9: 插入硬币钱箱;
// 10: 拔出纸币钱箱;
// 11: 插入纸币钱箱;
// 12: 拔出票箱;   
// 13: 插入票箱;
// 14: BOM班次开始
// 15: BOM班次结束

bool_t
xdr_ARFileTag_t (XDR *xdrs, ARFileTag_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 设备寄存器字段

bool_t
xdr_ARItem_t (XDR *xdrs, ARItem_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 0: 现金支付; 1: 储值卡支付; 2: 银行卡支付

bool_t
xdr_Paymentmeans_t (XDR *xdrs, Paymentmeans_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 0：身份证
// 1：学生证
// 2：残疾人证
// 3：军官证
// 4：老人证
// 5：护照
// 6：入境证

bool_t
xdr_IdentificationType_t (XDR *xdrs, IdentificationType_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 票卡物理编号
//TicketPhyID_t 共8个字节
//U64_t从高位到低位8个字节分别表示如下：
//1. 高位首字节: 票卡分类(ChipType_t)
//2. 如果票卡物理编号为7个字节，则：
//高位第二字节到最后一个字节（7个字节）表示为票卡高位到低位的7个字节。
//3. 如果票卡物理编号为4个字节，则：
//   1）高位起第2、3、4字节到全部填写0x00.
//   2）高位起第5、6、7、8字节到填写票卡高位到低位的4个字节。

bool_t
xdr_TicketPhyID_t (XDR *xdrs, TicketPhyID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, &objp->TicketPhyID_t_LO))
		 return FALSE;
	 if (!xdr_U32_t (xdrs, &objp->TicketPhyID_t_HI))
		 return FALSE;
	return TRUE;
}
// 一卡通用户卡应用序列号
// 一卡通文档中记录使用16个BCD码
// 其前8个BCD数字，拆分为4个字节的HEX打印码，分别对应YKTTicketAPPID_t_HO的高位到低位的4个字节
// 其后8个BCD数字，拆分为4个字节的HEX打印码，分别对应YKTTicketAPPID_t_IO的高位到低位的4个字节
// 例如户卡应用序列号为1122334455667788则对应为：
// YKTTicketAPPID_HI为0x11223344
// YKTTicketAPPID_LO为0x55667788

bool_t
xdr_YKTTicketAPPID_t (XDR *xdrs, YKTTicketAPPID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, &objp->YKTTicketAPPID_t_LO))
		 return FALSE;
	 if (!xdr_U32_t (xdrs, &objp->YKTTicketAPPID_t_HI))
		 return FALSE;
	return TRUE;
}
// 票卡印刷号，目前只有一票通储值票需要票卡卡面印刷号
// 按照规范的定义，暂定为“储值票卡卡面印刷号：2位厂商编码+2位产品编码+6位日期+1位批次号+5位流水号；”
// 具体内容待定

bool_t
xdr_TicketCoverPrintNumber_t (XDR *xdrs, TicketCoverPrintNumber_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->TicketCoverPrintNumber, 32,
		sizeof (U8_t), (xdrproc_t) xdr_U8_t))
		 return FALSE;
	return TRUE;
}
// 进出站交易标志位
// 0：进站交易；1：出站交易

bool_t
xdr_EntryExitBit_t (XDR *xdrs, EntryExitBit_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
// 票卡逻辑卡号
//使用规则
//TicketLogicalID_HI-从高位到低位依次为：前导码(U8_t)+卡印刷类型(U8_t)+批次日期(Date2_t)
//TicketLogicalID_LO-从高位到低位依次为：批次号(U8_t)+批次流水号(U16_t)+校验码(U8_t)
//其中单程票前导码1，储值票前导码6
//校验码前15位异或，异或后按10取模

bool_t
xdr_TicketLogicalID_t (XDR *xdrs, TicketLogicalID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, &objp->TicketLogicalID_HI))
		 return FALSE;
	 if (!xdr_U32_t (xdrs, &objp->TicketLogicalID_LO))
		 return FALSE;
	return TRUE;
}
// MD5码一共16个字节，表示为MD5[0]到MD5[15]
// 在XDR文件中，使用4个的方式来定义
// MD5Tag[0]的4个字节从高位到低位分表为：存放MD5[0]、MD5[1]、MD5[2]、MD5[3]
// MD5Tag[1]的4个字节从高位到低位分表为：存放MD5[4]、MD5[5]、MD5[6]、MD5[7]
// MD5Tag[2]的4个字节从高位到低位分表为：存放MD5[8]、MD5[9]、MD5[10]、MD5[11]
// MD5Tag[3]的4个字节从高位到低位分表为：存放MD5[12]、MD5[13]、MD5[14]、MD5[15]
// 文件格式为【[原文]+16个字节的MD5】

bool_t
xdr_MD5_t (XDR *xdrs, MD5_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->MD5Tag, 4,
		sizeof (U32_t), (xdrproc_t) xdr_U32_t))
		 return FALSE;
	return TRUE;
}
// ---------------------------------------------------------------------------------------
// ---- 库存文件类型
// ---------------------------------------------------------------------------------------

bool_t
xdr_StockFileType_t (XDR *xdrs, StockFileType_t *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TicketDirClassID_t (XDR *xdrs, TicketDirClassID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U16_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TicketCatalogID_t (XDR *xdrs, TicketCatalogID_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U16_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_InOutType_t (XDR *xdrs, InOutType_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_InOutFlag_t (XDR *xdrs, InOutFlag_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U8_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_BatchNumber_t (XDR *xdrs, BatchNumber_t *objp)
{
	register int32_t *buf;

	 if (!xdr_U32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
#ifdef __cplusplus
}
#endif

//#endif
