/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "xdrEOD.h"
/*************************************************************************************************************

   苏州市轨道交通线网AFC技术规程

   Title       : xdrEOD.h
   @Version    : 2.0.0
   @author     : 宁哲
   @date       : 2010/09/26
   Description : 定义系统的设备生成文件及参数文件格式
**************************************************************************************************************/
/*               EVOLUTIONS :
**************************************************************************************************************
*  Date        *  Author              * Changes
*---------------------------------------------------------------------------------
* 2010/01/07   *  宁哲                * 1.0.0 生成文档
* 2010/01/07   *  宁哲                * 1.0.1 完善文档内容
* 2010/01/14   *  宁哲                * 1.0.2 增加LCC_System_t结构
*                                       为所有的多媒体文件增加MD5校验码。XDR文件末尾自带MD5码用于文件完整性校验。
*                                       增加 DiskQuo_t、ReaderErrorConstraint_t、BanknoteAcceptorParm_t CoinModuleParam_t、IntrusionTimeoutAfterDoorOpen
*                                       增加KeyVersionID、PassengerParam_t、MultiRideParam_t
* 2010/02/01   *  宁哲                * 1.0.3 增加对CPU储值票的相关支持
* 2010/03/02   *  宁哲                * 1.0.5 增加票务处理相关字段
* 2010/04/20   *  宁哲                * 1.0.6 合并车站信息Ext结构
*                                       EODFile_t改为单EODParameter，即每个EOD文件只能放置一个EODParameter结构
*                                       增加MD5校验码
*                                       更新EOD主控文件格式
*                                       将操作员权限列表从清分中心数据Move到线路
*                                       优化TVM乘客界面参数
* 2010/04/20   *  宁哲                * 1.0.7 增加一卡通黑名单
* 2010/05/08   *  宁哲                * 1.0.8 调整罚款参数
* 2010/05/11   *  宁哲                * 1.0.9 格式内容调整
* 2010/07/08   *  宁哲                * 1.0.12  Line_t加到CCHS_NetworkTopologyParam_t中
*                                               删除MultiRideParam_t结构体
*                                               增加换乘车站TransferStationList
*                                               将PassengerParam改为PassengerParam<>
*                                               增加EntryAtSaleStation
*                                               取消TimeSyncInterval、PanaramaPic、PanaramaSelBtn_t、MultiRideParam_t
*                                               取消SectionTypeID、PassengerParam_t
* 2010/09/26   *  宁哲                * 1.0.14 修改CCHS_Sytem_t的定义
*                                               将TVMExpressIssueFare_t改为ExpressIssueFare_t，并移至CCHS_FareParam_t
* 2010/12/8   *  诸仕荣                * 2.0.5 修改CCHS_Sytem_t的“24小时连续运营的日期”为“单程当日延长时间”
*                                               在LCC_BOMParam_t中增加“单个文件交易最大数量”
*                                               修改MetroBlacklistEntry_t、MetroBlacklistRange_t、MetroIncrBlacklist_t的物理卡号为逻辑卡号
* 2010/12/21   *  诸仕荣                * 2.0.6 修改WaiverDateMasterConfigFile_t结构，去掉WaiverDate_t结构
* 2010/2/11    *  徐志君                * 2.0.7 修改StationModeInfo_t结构，增加降级模式结束时间 
---------------------------------------------------------------------------------*/
//#ifndef XDREOD_H
//#define XDREOD_H

#include "xdrBaseType.h"
// ---------------------------------------------------------------------------------------
// ---- EOD file definition
// ---------------------------------------------------------------------------------------
// 线路中文名称最长为32个Unicode字符，不足32个Unicode的超出部分全部填写0x0000
// 线路英文名称最长为128个字符，不足128个字节的超出部分全部填写0x00
// 启用标志位：0: 未启用；1: 启用

bool_t
xdr_Line_t (XDR *xdrs, Line_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_LineID_t (xdrs, &objp->LineID))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->LineCNName, 32,
		sizeof (CNChar_t), (xdrproc_t) xdr_CNChar_t))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->LineENName, 128,
		sizeof (ENChar_t), (xdrproc_t) xdr_ENChar_t))
		 return FALSE;
	 if (!xdr_Boolean_t (xdrs, &objp->EnableFlag))
		 return FALSE;
	return TRUE;
}
// 车站代码
// 车站中文名称最长为32个Unicode字符，不足32个Unicode的超出部分全部填写0x0000
// 车站英文名称最长为128个字符，不足128个字节的超出部分全部填写0x00
// 车站所在线路编号
// 启用标志位：0: 未启用；1: 启用

bool_t
xdr_Station_t (XDR *xdrs, Station_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_StationID_t (xdrs, &objp->StationID))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->StationCNName, 32,
		sizeof (CNChar_t), (xdrproc_t) xdr_CNChar_t))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->StationENName, 128,
		sizeof (ENChar_t), (xdrproc_t) xdr_ENChar_t))
		 return FALSE;
	 if (!xdr_LineID_t (xdrs, &objp->LineID))
		 return FALSE;
	 if (!xdr_Boolean_t (xdrs, &objp->EnableFlag))
		 return FALSE;
	return TRUE;
}
//	ZoneTypeID_t                             ZoneTypeID;                            /* 区域类别代码 */
// 区域中文名称最长为128个Unicode字符，不足128个Unicode的超出部分全部填写0x0000		
// 区域英文名称最长为128个字符，不足128个字节的超出部分全部填写0x00		
// 启用标志位：0: 未启用；1: 启用

bool_t
xdr_Zone_t (XDR *xdrs, Zone_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_ZoneID_t (xdrs, &objp->ZoneID))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->StationID.StationID_val, (u_int *) &objp->StationID.StationID_len, ~0,
		sizeof (StationID_t), (xdrproc_t) xdr_StationID_t))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->ZoneCNName, 128,
		sizeof (CNChar_t), (xdrproc_t) xdr_CNChar_t))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->ZoneENName, 128,
		sizeof (ENChar_t), (xdrproc_t) xdr_ENChar_t))
		 return FALSE;
	 if (!xdr_Boolean_t (xdrs, &objp->EnableFlag))
		 return FALSE;
	return TRUE;
}
//	SectionTypeID_t                          SectionTypeID;                         /* 区段类别代码，用于与TicketDefinition_t绑定 */
// 区段中文名称最长为32个Unicode字符，不足32个Unicode的超出部分全部填写0x0000		
// 区段英文名称最长为128个字符，不足128个字符的超出部分全部填写0x00		
// 启用标志位：0: 未启用；1: 启用

bool_t
xdr_Section_t (XDR *xdrs, Section_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_SectionID_t (xdrs, &objp->SectionID))
		 return FALSE;
	 if (!xdr_StationID_t (xdrs, &objp->StationID1))
		 return FALSE;
	 if (!xdr_StationID_t (xdrs, &objp->StationID2))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->SectionCNName, 32,
		sizeof (CNChar_t), (xdrproc_t) xdr_CNChar_t))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->SectionENName, 128,
		sizeof (ENChar_t), (xdrproc_t) xdr_ENChar_t))
		 return FALSE;
	 if (!xdr_Boolean_t (xdrs, &objp->EnableFlag))
		 return FALSE;
	return TRUE;
}
// 换乘车站用于判断单程票是否在购票车站进站

bool_t
xdr_TransferStation_t (XDR *xdrs, TransferStation_t *objp)
{
	register int32_t *buf;

	 if (!xdr_TransferStationID_t (xdrs, &objp->TransferStationID))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->StationID.StationID_val, (u_int *) &objp->StationID.StationID_len, ~0,
		sizeof (StationID_t), (xdrproc_t) xdr_StationID_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_CCHS_NetworkTopologyParam_t (XDR *xdrs, CCHS_NetworkTopologyParam_t *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->Line.Line_val, (u_int *) &objp->Line.Line_len, ~0,
		sizeof (Line_t), (xdrproc_t) xdr_Line_t))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->Station.Station_val, (u_int *) &objp->Station.Station_len, ~0,
		sizeof (Station_t), (xdrproc_t) xdr_Station_t))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->Zone.Zone_val, (u_int *) &objp->Zone.Zone_len, ~0,
		sizeof (Zone_t), (xdrproc_t) xdr_Zone_t))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->Section.Section_val, (u_int *) &objp->Section.Section_len, ~0,
		sizeof (Section_t), (xdrproc_t) xdr_Section_t))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->TransferStation.TransferStation_val, (u_int *) &objp->TransferStation.TransferStation_len, ~0,
		sizeof (TransferStation_t), (xdrproc_t) xdr_TransferStation_t))
		 return FALSE;
	return TRUE;
}
//struct PassengerParam_t{
//	PassengerTypeID_t                        PassengerTypeID;                       /* 乘客类别编码 */
// 乘客类别中文名称最长为16个Unicode字符，不足16个Unicode的超出部分全部填写0x0000
//	CNChar_t                                 PassengerTypeCNName[16];               /* 乘客类别中文名称 */
// 乘客类别英文名称最长为32个字符，不足32个字节的超出部分全部填写0x00
//	ENChar_t                                 PassengerTypeENName[32];               /* 乘客类型英文简称 */	
//};
//struct MultiRideParam_t{
//	MultiRideTypeID_t                        MultiRideTypeID;                       /* 计次票乘客次数类别 */
//	MultiRideNumber_t                        MultiRideNumber;                       /* 计次票乘客次数 */      	
//};
// 车票中文名称最长为16个Unicode字符，不足16个Unicode的超出部分全部填写0x0000
// 车票英文名称最长为32个字符，不足32个字节的超出部分全部填写0x00
//	PassengerTypeID_t                        PassengerTypeID;                       /* 乘客类别，仅用于BOM界面选择，与票价无关 */
// 0: 无使用范围限制
// 1: 在限定的区域使用 
// 2: 在限定的区段使用
//	ZoneID_t                                 ZoneID;                                /* 区域类别编号 */	
//	SectionTypeID_t                          SectionTypeID;                         /* 区段类别编号 */	
//	MultiRideTypeID_t                        MultiRideTypeID;                       /* 计次类型 */	
// 0: 非纪念票; 1: 纪念票
// 0: 非记名票; 1: 记名票
// 0: 不可充值；1: 可充值
//	FareTier_t                               MaxFareTier;                           /* 最大的里程数 */
//	Boolean_t                                ExtendAuthorized;                      /* 是否允许延期 */
// 0:不优惠; 1: 联乘优惠
// 0: 未启用；1:启用

bool_t
xdr_TicketDefinition_t (XDR *xdrs, TicketDefinition_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_TicketType_t (xdrs, &objp->TicketType))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->TicketTypeCNName, 16,
		sizeof (CNChar_t), (xdrproc_t) xdr_CNChar_t))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->TicketTypeENName, 32,
		sizeof (ENChar_t), (xdrproc_t) xdr_ENChar_t))
		 return FALSE;
	 if (!xdr_TicketFamily_t (xdrs, &objp->TicketFamily))
		 return FALSE;
	 if (!xdr_AreaTicketFlag_t (xdrs, &objp->AreaTicketFlag))
		 return FALSE;
	 if (!xdr_MultiRideNumber_t (xdrs, &objp->MultiRideNumber))
		 return FALSE;
	 if (!xdr_ValueCent_t (xdrs, &objp->SaleFixedPrice))
		 return FALSE;
	 if (!xdr_Boolean_t (xdrs, &objp->SouvenirFlag))
		 return FALSE;
	 if (!xdr_Boolean_t (xdrs, &objp->MemberTicketFlag))
		 return FALSE;
	 if (!xdr_SoundDisplayID_t (xdrs, &objp->SoundDisplayID))
		 return FALSE;
	 if (!xdr_ConcessionalLampID_t (xdrs, &objp->ConcessionalLampID))
		 return FALSE;
	 if (!xdr_Boolean_t (xdrs, &objp->AddValueAuthorized))
		 return FALSE;
	 if (!xdr_ValueCent_t (xdrs, &objp->MinAddValue))
		 return FALSE;
	 if (!xdr_ValueCent_t (xdrs, &objp->MaxRemainingValue))
		 return FALSE;
	 if (!xdr_ValueCent_t (xdrs, &objp->MinEntryAmount))
		 return FALSE;
	 if (!xdr_ValueCent_t (xdrs, &objp->MinExitAmount))
		 return FALSE;
	 if (!xdr_ValueCent_t (xdrs, &objp->DepositValue))
		 return FALSE;
	 if (!xdr_ValueCent_t (xdrs, &objp->DepreciationValue))
		 return FALSE;
	 if (!xdr_Boolean_t (xdrs, &objp->RefundAuthorized))
		 return FALSE;
	 if (!xdr_ValueCent_t (xdrs, &objp->MaxImmediateRefundAmount))
		 return FALSE;
	 if (!xdr_ValueCent_t (xdrs, &objp->RefundCharge))
		 return FALSE;
	 if (!xdr_MultiRideNumber_t (xdrs, &objp->MaxRideNumber))
		 return FALSE;
	 if (!xdr_DurationMode_t (xdrs, &objp->DurationMode))
		 return FALSE;
	 if (!xdr_Duration_t (xdrs, &objp->Duration))
		 return FALSE;
	 if (!xdr_Date2_t (xdrs, &objp->FixedEndDate))
		 return FALSE;
	 if (!xdr_Seconds_t (xdrs, &objp->PeriodofFreeAdjustForNoExit))
		 return FALSE;
	 if (!xdr_ValueCent_t (xdrs, &objp->OverstayingFeeValue))
		 return FALSE;
	 if (!xdr_ValueCent_t (xdrs, &objp->NoExitFeeValue))
		 return FALSE;
	 if (!xdr_ValueCent_t (xdrs, &objp->SurchargeStationMisMatch))
		 return FALSE;
	 if (!xdr_ConcessionType_t (xdrs, &objp->ConcessionType))
		 return FALSE;
	 if (!xdr_Boolean_t (xdrs, &objp->EnableFlag))
		 return FALSE;
	return TRUE;
}
// 提示音文件名最长为8个字符，不足8个字符的超出部分全部填写0x00		

bool_t
xdr_SoundDisplay_t (XDR *xdrs, SoundDisplay_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_SoundDisplayID_t (xdrs, &objp->SoundDisplayID))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->SoundDisplayFileName, 8,
		sizeof (ENChar_t), (xdrproc_t) xdr_ENChar_t))
		 return FALSE;
	 if (!xdr_MD5_t (xdrs, &objp->SoundDisplayFileMD5))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ChipDefinition_t (XDR *xdrs, ChipDefinition_t *objp)
{
	register int32_t *buf;

	 if (!xdr_ChipType_t (xdrs, &objp->ChipType))
		 return FALSE;
	 if (!xdr_Duration_t (xdrs, &objp->PhycialValidityPeriod))
		 return FALSE;
	 if (!xdr_U32_t (xdrs, &objp->MaxChipIONumber))
		 return FALSE;
	return TRUE;
}
//	PassengerParam_t                         PassengerParam<>;                      /* 乘客类型定义 */

bool_t
xdr_CCHS_TicketParam_t (XDR *xdrs, CCHS_TicketParam_t *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->ChipDefinition.ChipDefinition_val, (u_int *) &objp->ChipDefinition.ChipDefinition_len, ~0,
		sizeof (ChipDefinition_t), (xdrproc_t) xdr_ChipDefinition_t))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->TicketDefinition.TicketDefinition_val, (u_int *) &objp->TicketDefinition.TicketDefinition_len, ~0,
		sizeof (TicketDefinition_t), (xdrproc_t) xdr_TicketDefinition_t))
		 return FALSE;
	 if (!xdr_KeyVersionID_t (xdrs, &objp->KeyVersionID))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_BankAddingValuePara_t (XDR *xdrs, BankAddingValuePara_t *objp)
{
	register int32_t *buf;

	 if (!xdr_ValueCent_t (xdrs, &objp->BankCardPaymentMinAmount))
		 return FALSE;
	 if (!xdr_ValueCent_t (xdrs, &objp->BankCardPaymentMaxAmount))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TimeInterval_t (XDR *xdrs, TimeInterval_t *objp)
{
	register int32_t *buf;

	 if (!xdr_TimeIntervalID_t (xdrs, &objp->TimeIntervalID))
		 return FALSE;
	 if (!xdr_SecondsSinceMidNight_t (xdrs, &objp->TimeIntervalValue))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_FareGroup_t (XDR *xdrs, FareGroup_t *objp)
{
	register int32_t *buf;

	 if (!xdr_TicketFareTypeID_t (xdrs, &objp->TicketFareTypeID))
		 return FALSE;
	 if (!xdr_DateTypeID_t (xdrs, &objp->DateTypeID))
		 return FALSE;
	 if (!xdr_TimeIntervalID_t (xdrs, &objp->TimeIntervalID))
		 return FALSE;
	 if (!xdr_FareGroupID_t (xdrs, &objp->FareGroupID))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_BaseFare_t (XDR *xdrs, BaseFare_t *objp)
{
	register int32_t *buf;

	 if (!xdr_FareGroupID_t (xdrs, &objp->FareGroupID))
		 return FALSE;
	 if (!xdr_FareTier_t (xdrs, &objp->FareTier))
		 return FALSE;
	 if (!xdr_ValueCent_t (xdrs, &objp->FareAmount))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TicketFareType_t (XDR *xdrs, TicketFareType_t *objp)
{
	register int32_t *buf;

	 if (!xdr_TicketType_t (xdrs, &objp->TicketType))
		 return FALSE;
	 if (!xdr_SP_t (xdrs, &objp->ServiceProvider))
		 return FALSE;
	 if (!xdr_TicketFareTypeID_t (xdrs, &objp->TicketFareTypeID))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_FareTierTimeTable_t (XDR *xdrs, FareTierTimeTable_t *objp)
{
	register int32_t *buf;

	 if (!xdr_FareTier_t (xdrs, &objp->FareTier))
		 return FALSE;
	 if (!xdr_Seconds_t (xdrs, &objp->AllowedTravelPeriod))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_FareTierMatrix_t (XDR *xdrs, FareTierMatrix_t *objp)
{
	register int32_t *buf;

	 if (!xdr_FareTier_t (xdrs, &objp->FareTier))
		 return FALSE;
	 if (!xdr_StationID_t (xdrs, &objp->StationID1))
		 return FALSE;
	 if (!xdr_StationID_t (xdrs, &objp->StationID2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ExpressIssueFare_t (XDR *xdrs, ExpressIssueFare_t *objp)
{
	register int32_t *buf;

	 if (!xdr_ValueCent_t (xdrs, &objp->FareAmount))
		 return FALSE;
	 if (!xdr_FareTier_t (xdrs, &objp->FareTier))
		 return FALSE;
	return TRUE;
}
// 专用于TVM金额快速购票

bool_t
xdr_CCHS_FareParam_t (XDR *xdrs, CCHS_FareParam_t *objp)
{
	register int32_t *buf;

	 if (!xdr_BankAddingValuePara_t (xdrs, &objp->BankAddingValuePara))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->FareGroup.FareGroup_val, (u_int *) &objp->FareGroup.FareGroup_len, ~0,
		sizeof (FareGroup_t), (xdrproc_t) xdr_FareGroup_t))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->FareTierMatrixData.FareTierMatrixData_val, (u_int *) &objp->FareTierMatrixData.FareTierMatrixData_len, ~0,
		sizeof (FareTierMatrix_t), (xdrproc_t) xdr_FareTierMatrix_t))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->BaseFare.BaseFare_val, (u_int *) &objp->BaseFare.BaseFare_len, ~0,
		sizeof (BaseFare_t), (xdrproc_t) xdr_BaseFare_t))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->TicketFareType.TicketFareType_val, (u_int *) &objp->TicketFareType.TicketFareType_len, ~0,
		sizeof (TicketFareType_t), (xdrproc_t) xdr_TicketFareType_t))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->ExpressIssueFare.ExpressIssueFare_val, (u_int *) &objp->ExpressIssueFare.ExpressIssueFare_len, ~0,
		sizeof (ExpressIssueFare_t), (xdrproc_t) xdr_ExpressIssueFare_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SpecialDate_t (XDR *xdrs, SpecialDate_t *objp)
{
	register int32_t *buf;

	 if (!xdr_Date2_t (xdrs, &objp->SpecialDate))
		 return FALSE;
	 if (!xdr_DateTypeID_t (xdrs, &objp->DateTypeID))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_CCHS_CalendarParam_t (XDR *xdrs, CCHS_CalendarParam_t *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->SpecialDate.SpecialDate_val, (u_int *) &objp->SpecialDate.SpecialDate_len, ~0,
		sizeof (SpecialDate_t), (xdrproc_t) xdr_SpecialDate_t))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->TimeInterval.TimeInterval_val, (u_int *) &objp->TimeInterval.TimeInterval_len, ~0,
		sizeof (TimeInterval_t), (xdrproc_t) xdr_TimeInterval_t))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->FareTierTimeTable.FareTierTimeTable_val, (u_int *) &objp->FareTierTimeTable.FareTierTimeTable_len, ~0,
		sizeof (FareTierTimeTable_t), (xdrproc_t) xdr_FareTierTimeTable_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ConcessionalLampType_t (XDR *xdrs, ConcessionalLampType_t *objp)
{
	register int32_t *buf;

	 if (!xdr_ConcessionalLampID_t (xdrs, &objp->ConcessionalLampID))
		 return FALSE;
	 if (!xdr_LampColorTypeID_t (xdrs, &objp->LampColorTypeID))
		 return FALSE;
	 if (!xdr_FrequencyWithinMin_t (xdrs, &objp->Frequency))
		 return FALSE;
	 if (!xdr_Seconds_t (xdrs, &objp->DisplayPeriod))
		 return FALSE;
	return TRUE;
}
// AGM提示音列表
// AGM显示灯列表

bool_t
xdr_CCHS_AGMParam_t (XDR *xdrs, CCHS_AGMParam_t *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->SoundDisplay.SoundDisplay_val, (u_int *) &objp->SoundDisplay.SoundDisplay_len, ~0,
		sizeof (SoundDisplay_t), (xdrproc_t) xdr_SoundDisplay_t))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->ConcessionalLampType.ConcessionalLampType_val, (u_int *) &objp->ConcessionalLampType.ConcessionalLampType_len, ~0,
		sizeof (ConcessionalLampType_t), (xdrproc_t) xdr_ConcessionalLampType_t))
		 return FALSE;
	 if (!xdr_Boolean_t (xdrs, &objp->EntryAtSaleStation))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_CCHS_AVMParam_t (XDR *xdrs, CCHS_AVMParam_t *objp)
{
	register int32_t *buf;

	 if (!xdr_ValueCent_t (xdrs, &objp->MaxAddingValueAmount))
		 return FALSE;
	 if (!xdr_ValueCent_t (xdrs, &objp->AddingValueAmountConstraint))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_UploadParam_t (XDR *xdrs, UploadParam_t *objp)
{
	register int32_t *buf;

	 if (!xdr_Seconds_t (xdrs, &objp->YKTUDUploadInterval))
		 return FALSE;
	 if (!xdr_Seconds_t (xdrs, &objp->CCHSUDUploadInterval))
		 return FALSE;
	 if (!xdr_Seconds_t (xdrs, &objp->CCHSFINUploadInterval))
		 return FALSE;
	 if (!xdr_Seconds_t (xdrs, &objp->CCHSARUploadInterval))
		 return FALSE;
	 if (!xdr_Seconds_t (xdrs, &objp->CCHSEVTUploadInterval))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_DiskQuo_t (XDR *xdrs, DiskQuo_t *objp)
{
	register int32_t *buf;

	 if (!xdr_Percentage_t (xdrs, &objp->DiskAlmostFullLimit))
		 return FALSE;
	 if (!xdr_Percentage_t (xdrs, &objp->DiskFullLimit))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ReaderErrorConstraint_t (XDR *xdrs, ReaderErrorConstraint_t *objp)
{
	register int32_t *buf;

	 if (!xdr_Times_t (xdrs, &objp->MetroIOMaxConsecutiveError))
		 return FALSE;
	 if (!xdr_Times_t (xdrs, &objp->YKTIOMaxConsecutiveError))
		 return FALSE;
	 if (!xdr_Times_t (xdrs, &objp->CashCardIOMaxConsecutiveError))
		 return FALSE;
	return TRUE;
}
//	ReaderErrorConstraint_t                  ReaderErrorConstraint;                 /* 读写器读写控制信息 */

bool_t
xdr_LCC_AGMParam_t (XDR *xdrs, LCC_AGMParam_t *objp)
{
	register int32_t *buf;

	 if (!xdr_TransactionNb_t (xdrs, &objp->MaxUDAmount))
		 return FALSE;
	 if (!xdr_Duration_t (xdrs, &objp->TxnValidityDays))
		 return FALSE;
	 if (!xdr_UploadParam_t (xdrs, &objp->AGMUploadParam))
		 return FALSE;
	 if (!xdr_DiskQuo_t (xdrs, &objp->DiskQuo))
		 return FALSE;
	 if (!xdr_TicketQuantity_t (xdrs, &objp->CSTStockAlmostFullLimit))
		 return FALSE;
	 if (!xdr_TicketQuantity_t (xdrs, &objp->CSTStockAlreadyFullLimit))
		 return FALSE;
	return TRUE;
}
//struct ScreenSize_t {                                                               /*--- 屏幕尺寸类型 ---*/
//	CoordinateUnit_t                         ScreenWidth;                           /* 屏幕宽度 */
//	CoordinateUnit_t                         ScreenHeight;                          /* 屏幕高度 */
//};

bool_t
xdr_CaptionDispay_t (XDR *xdrs, CaptionDispay_t *objp)
{
	register int32_t *buf;

	 if (!xdr_CoordinateUnit_t (xdrs, &objp->DateCaptionX))
		 return FALSE;
	 if (!xdr_CoordinateUnit_t (xdrs, &objp->DateCaptionY))
		 return FALSE;
	 if (!xdr_CoordinateUnit_t (xdrs, &objp->DateCaptionWidth))
		 return FALSE;
	 if (!xdr_CoordinateUnit_t (xdrs, &objp->DateCaptionHeight))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ExpressBtn_t (XDR *xdrs, ExpressBtn_t *objp)
{
	register int32_t *buf;

	 if (!xdr_ExpressBtnIndex_t (xdrs, &objp->ExpressBtnIndex))
		 return FALSE;
	 if (!xdr_ValueCent_t (xdrs, &objp->ExpressBtnValue))
		 return FALSE;
	 if (!xdr_CaptionDispay_t (xdrs, &objp->ExpressBtn))
		 return FALSE;
	 if (!xdr_Boolean_t (xdrs, &objp->ExpressBtn_tEnable))
		 return FALSE;
	return TRUE;
}
//struct PanaramaPic_t {                                                              /*--- 路网全景图片 ---*/
// 路网全景中文图片文件名最长为16个Unicode字符，不足16个字节的超出部分全部填写0x00		
//	ENChar_t                                 PanaramaCNPicName[16];                 /* 路网全景中文图片文件名 */
//	MD5_t                                    PanaramaCNPicMD5;                      /* 路网全景中文图片文件整个文件二进制内容的MD5码 */
// 路网全景英文图片文件名最长为16个字节，不足16个字节的超出部分全部填写0x00		
//	ENChar_t                                 PanaramaENPicName[16];                 /* 路网全景英文图片文件名 */
//	MD5_t                                    PanaramaENPicMD5;                      /* 路网全景英文图片文件整个文件二进制内容的MD5码 */
//	CaptionDispay_t                          PanaramaPicDisplay;                    /* 路网图片显示坐标信息 */
//};
// 线路区域中文图片名最长为16个Unicode字符，不足16个字节的超出部分全部填写0x00		
// 线路区域英文图片名最长为16个字节，不足16个字节的超出部分全部填写0x00

bool_t
xdr_LineZoneSelBtn_t (XDR *xdrs, LineZoneSelBtn_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_LineZoneSelBtnID_t (xdrs, &objp->LineZoneSelBtnID))
		 return FALSE;
	 if (!xdr_CaptionDispay_t (xdrs, &objp->LineZoneSelBtnDisplay))
		 return FALSE;
	 if (!xdr_Boolean_t (xdrs, &objp->LineZoneSelBtnEnableFlag))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->LineZoneCNPicName, 16,
		sizeof (ENChar_t), (xdrproc_t) xdr_ENChar_t))
		 return FALSE;
	 if (!xdr_MD5_t (xdrs, &objp->LineZoneCNPicMD5))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->LineZoneENPicName, 16,
		sizeof (ENChar_t), (xdrproc_t) xdr_ENChar_t))
		 return FALSE;
	 if (!xdr_MD5_t (xdrs, &objp->LineZoneENPicMD5))
		 return FALSE;
	 if (!xdr_CaptionDispay_t (xdrs, &objp->LineZonePicDisplay))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_StationSelBtn_t (XDR *xdrs, StationSelBtn_t *objp)
{
	register int32_t *buf;

	 if (!xdr_StationID_t (xdrs, &objp->StationID))
		 return FALSE;
	 if (!xdr_LineZoneSelBtnID_t (xdrs, &objp->LineZoneSelBtnID))
		 return FALSE;
	 if (!xdr_CaptionDispay_t (xdrs, &objp->StationSelBtnDisplay))
		 return FALSE;
	 if (!xdr_Boolean_t (xdrs, &objp->StationSelBtnEnable))
		 return FALSE;
	return TRUE;
}
//	ScreenSize_t                             ScreenSize;                            /* 屏幕尺寸参数 */
//	PanaramaPic_t                            PanaramaPic;                           /* 路网全景图片(首页)类型 */
//	CaptionDispay_t                          PanaramaSelBtn_t;                      /* 路网全景图片(首页)选择按钮 */

bool_t
xdr_TVMLineStationPic_t (XDR *xdrs, TVMLineStationPic_t *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->ExpressBtn.ExpressBtn_val, (u_int *) &objp->ExpressBtn.ExpressBtn_len, ~0,
		sizeof (ExpressBtn_t), (xdrproc_t) xdr_ExpressBtn_t))
		 return FALSE;
	 if (!xdr_CaptionDispay_t (xdrs, &objp->DateCaptionDispay))
		 return FALSE;
	 if (!xdr_CaptionDispay_t (xdrs, &objp->TimeCaptionDispay))
		 return FALSE;
	 if (!xdr_CaptionDispay_t (xdrs, &objp->LocalStation))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->LineZoneSelBtn.LineZoneSelBtn_val, (u_int *) &objp->LineZoneSelBtn.LineZoneSelBtn_len, ~0,
		sizeof (LineZoneSelBtn_t), (xdrproc_t) xdr_LineZoneSelBtn_t))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->StationSelBtn.StationSelBtn_val, (u_int *) &objp->StationSelBtn.StationSelBtn_len, ~0,
		sizeof (StationSelBtn_t), (xdrproc_t) xdr_StationSelBtn_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_CCHS_TVMParam_t (XDR *xdrs, CCHS_TVMParam_t *objp)
{
	register int32_t *buf;

	 if (!xdr_TVMLineStationPic_t (xdrs, &objp->TVMLineStationPic))
		 return FALSE;
	return TRUE;
}
// 广告多媒体播放文件名最长为16个字符，不足16个字节的超出部分全部填写0x00		

bool_t
xdr_ADItem_t (XDR *xdrs, ADItem_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_ADItemID_t (xdrs, &objp->ADItemID))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->ADItemFileName, 16,
		sizeof (ENChar_t), (xdrproc_t) xdr_ENChar_t))
		 return FALSE;
	 if (!xdr_MD5_t (xdrs, &objp->ADItemFileMD5))
		 return FALSE;
	 if (!xdr_MultiMediaType_t (xdrs, &objp->MultiMediaType))
		 return FALSE;
	return TRUE;
}
// 找零器报警数量 
// 找零器停止找零数量 
// 硬币接受报警数量
// 硬币接受上限数量
// TVM可接受的硬币种类：50表示5角；100表示1元；

bool_t
xdr_CoinModuleParam_t (XDR *xdrs, CoinModuleParam_t *objp)
{
	register int32_t *buf;

	 if (!xdr_CoinQuantity_t (xdrs, &objp->HopperAlmostEmptyLimit))
		 return FALSE;
	 if (!xdr_CoinQuantity_t (xdrs, &objp->HopperEmptyLimit))
		 return FALSE;
	 if (!xdr_CoinQuantity_t (xdrs, &objp->CoinBoxAlmostFullLimit))
		 return FALSE;
	 if (!xdr_CoinQuantity_t (xdrs, &objp->CoinBoxFullLimit))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->AcceptableCoinValue.AcceptableCoinValue_val, (u_int *) &objp->AcceptableCoinValue.AcceptableCoinValue_len, ~0,
		sizeof (ValueCent_t), (xdrproc_t) xdr_ValueCent_t))
		 return FALSE;
	return TRUE;
}
// 纸币接受报警数量
// 纸币接受上限数量 	
// TVM可接受的纸币种类：100表示1元；200表示2元；以此类推

bool_t
xdr_BanknoteAcceptorParm_t (XDR *xdrs, BanknoteAcceptorParm_t *objp)
{
	register int32_t *buf;

	 if (!xdr_BanknoteQuantity_t (xdrs, &objp->BankNoteBoxAlmostFullLimit))
		 return FALSE;
	 if (!xdr_BanknoteQuantity_t (xdrs, &objp->BankNoteBoxFullLimit))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->AcceptableBankNoteValue.AcceptableBankNoteValue_val, (u_int *) &objp->AcceptableBankNoteValue.AcceptableBankNoteValue_len, ~0,
		sizeof (ValueCent_t), (xdrproc_t) xdr_ValueCent_t))
		 return FALSE;
	return TRUE;
}
// 单个文件最大交易数量
// 交易在本地保存的有效天数
// TVM数据上传参数	
// 硬盘容量控制上限	
// 读写器读写控制信息
//	ReaderErrorConstraint_t                  ReaderErrorConstraint;                 
// 纸币接收器参数
// 纸币模块参数
// 是否支持使用储值票付款 
// 最大硬币找零金额
// 最大纸币找零金额 
// 单程票不足报警数量 
// 进入到广告模式的等待时间
// 广告信息
// 广告播放方式 
// 打开维护门后，判定闯入发生的时间段
// 温度上限
// 判定温度过高越界时，设备是否自动关机
// 打印机出现故障时，设备是否继续正常工作，或是转入暂停服务

bool_t
xdr_LCC_TVMParam_t (XDR *xdrs, LCC_TVMParam_t *objp)
{
	register int32_t *buf;

	 if (!xdr_TransactionNb_t (xdrs, &objp->MaxUDAmount))
		 return FALSE;
	 if (!xdr_Duration_t (xdrs, &objp->TxnValidityDays))
		 return FALSE;
	 if (!xdr_UploadParam_t (xdrs, &objp->TVMUploadParam))
		 return FALSE;
	 if (!xdr_DiskQuo_t (xdrs, &objp->DiskQuo))
		 return FALSE;
	 if (!xdr_BanknoteAcceptorParm_t (xdrs, &objp->BanknoteAcceptorParm))
		 return FALSE;
	 if (!xdr_CoinModuleParam_t (xdrs, &objp->CoinModuleParam))
		 return FALSE;
	 if (!xdr_Boolean_t (xdrs, &objp->PaymentMeans))
		 return FALSE;
	 if (!xdr_ValueCent_t (xdrs, &objp->MaxNbOfCoinChangeOut))
		 return FALSE;
	 if (!xdr_ValueCent_t (xdrs, &objp->MaxNbOfBanknoteChangeOut))
		 return FALSE;
	 if (!xdr_TicketQuantity_t (xdrs, &objp->CSTStockAlmostEmptyLimit))
		 return FALSE;
	 if (!xdr_Seconds_t (xdrs, &objp->TimeoutBeforeADLoad))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->ADItem.ADItem_val, (u_int *) &objp->ADItem.ADItem_len, ~0,
		sizeof (ADItem_t), (xdrproc_t) xdr_ADItem_t))
		 return FALSE;
	 if (!xdr_U8_t (xdrs, &objp->ADPlayMeans))
		 return FALSE;
	 if (!xdr_Seconds_t (xdrs, &objp->IntrusionTimeoutBeforeLogon))
		 return FALSE;
	 if (!xdr_Centidegree_t (xdrs, &objp->TemperatureMaxLimitation))
		 return FALSE;
	 if (!xdr_Boolean_t (xdrs, &objp->AutomaticSwitchOff))
		 return FALSE;
	 if (!xdr_Boolean_t (xdrs, &objp->bOutOfServicePrintError))
		 return FALSE;
	return TRUE;
}
//struct BOMOperatorAuth_t{
//	ValueCent_t                              AuthorizationMaxValue;                 /* 授权最大金额 */	
//	ValueCent_t                              PerShiftMaxAddValue;                   /* 单班最大充值额度 */	
//};
// BOM直连CCHS通讯服务器的通讯信息
// CCHS通讯IP地址，最长为16字节，不足16个字节的超出部分全部填写0x00		
// CCHS通讯IP地址
// CCHS通讯TCP Server port

bool_t
xdr_CCHSCommunicationSrv_t (XDR *xdrs, CCHSCommunicationSrv_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->CCHSIPAddress, 20,
		sizeof (ENChar_t), (xdrproc_t) xdr_ENChar_t))
		 return FALSE;
	 if (!xdr_TCPPort_t (xdrs, &objp->CCHSTCPPort))
		 return FALSE;
	return TRUE;
}
// 自动转入退出时间 
// CCHSCommunicationSrv[0]: BOM认证服务
// CCHSCommunicationSrv[1]: 票卡充值密钥计算服务
// CCHSCommunicationSrv[2]: 票卡信息查询服务
// 其余的通讯信息暂作预留

bool_t
xdr_CCHS_BOMParam_t (XDR *xdrs, CCHS_BOMParam_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_TransactionNb_t (xdrs, &objp->MaxUDAmount))
		 return FALSE;
	 if (!xdr_Duration_t (xdrs, &objp->TxnValidityDays))
		 return FALSE;
	 if (!xdr_Seconds_t (xdrs, &objp->NoOperatorActionTimeOut))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->CCHSCommunicationSrv, 6,
		sizeof (CCHSCommunicationSrv_t), (xdrproc_t) xdr_CCHSCommunicationSrv_t))
		 return FALSE;
	 if (!xdr_Seconds_t (xdrs, &objp->PeriodOfFreeUpdateEntry))
		 return FALSE;
	 if (!xdr_ValueCent_t (xdrs, &objp->PerShiftMaxAddValue))
		 return FALSE;
	return TRUE;
}
// 单程票不足报警数量 
// BOM数据上传参数 
// 硬盘容量控制上限
// 读写器读写控制信息 
//	ReaderErrorConstraint_t                  ReaderErrorConstraint;                 
// 打印机出现故障时，设备是否继续正常工作,或是转入暂停服务
//	Boolean_t                                bOutOfServicePrintError;	

bool_t
xdr_LCC_BOMParam_t (XDR *xdrs, LCC_BOMParam_t *objp)
{
	register int32_t *buf;

	 if (!xdr_TransactionNb_t (xdrs, &objp->MaxUDAmount))
		 return FALSE;
	 if (!xdr_TicketQuantity_t (xdrs, &objp->CSTStockAlmostEmptyLimit))
		 return FALSE;
	 if (!xdr_UploadParam_t (xdrs, &objp->BOMUploadParam))
		 return FALSE;
	 if (!xdr_DiskQuo_t (xdrs, &objp->DiskQuo))
		 return FALSE;
	return TRUE;
}
// BOM数据上传参数 
// 硬盘容量控制上限
// 读写器读写控制信息
//	ReaderErrorConstraint_t                  ReaderErrorConstraint;                 

bool_t
xdr_LCC_AVMParam_t (XDR *xdrs, LCC_AVMParam_t *objp)
{
	register int32_t *buf;

	 if (!xdr_UploadParam_t (xdrs, &objp->AVMUploadParam))
		 return FALSE;
	 if (!xdr_DiskQuo_t (xdrs, &objp->DiskQuo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SysTimeSync_t (XDR *xdrs, SysTimeSync_t *objp)
{
	register int32_t *buf;

	 if (!xdr_Seconds_t (xdrs, &objp->TimeDeviationPeriod))
		 return FALSE;
	 if (!xdr_Seconds_t (xdrs, &objp->MinTimeDeviation))
		 return FALSE;
	 if (!xdr_Seconds_t (xdrs, &objp->MaxTimeDeviation))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OperatorGroup_t (XDR *xdrs, OperatorGroup_t *objp)
{
	register int32_t *buf;

	 if (!xdr_OperatorGroupID_t (xdrs, &objp->OperatorGroupID))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->EQPFuncID.EQPFuncID_val, (u_int *) &objp->EQPFuncID.EQPFuncID_len, ~0,
		sizeof (EQPFuncID_t), (xdrproc_t) xdr_EQPFuncID_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ACZone_t (XDR *xdrs, ACZone_t *objp)
{
	register int32_t *buf;

	 if (!xdr_ACZoneID_t (xdrs, &objp->ACZoneID))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->ACZoneStationList.ACZoneStationList_val, (u_int *) &objp->ACZoneStationList.ACZoneStationList_len, ~0,
		sizeof (StationID_t), (xdrproc_t) xdr_StationID_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OperatorList_t (XDR *xdrs, OperatorList_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_OperatorID_t (xdrs, &objp->OperatorID))
		 return FALSE;
	 if (!xdr_OperatorGroupID_t (xdrs, &objp->OperatorGroupID))
		 return FALSE;
	 if (!xdr_Date2_t (xdrs, &objp->ValidStartDate))
		 return FALSE;
	 if (!xdr_Date2_t (xdrs, &objp->ValidEndDate))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->Password, 8,
		sizeof (ENChar_t), (xdrproc_t) xdr_ENChar_t))
		 return FALSE;
	 if (!xdr_ACZoneID_t (xdrs, &objp->ACZoneID))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_StaffTicketGroupDefinition_t (XDR *xdrs, StaffTicketGroupDefinition_t *objp)
{
	register int32_t *buf;

	 if (!xdr_StaffGroupID_t (xdrs, &objp->StaffGroupID))
		 return FALSE;
	 if (!xdr_Date2_t (xdrs, &objp->ValidStartDate))
		 return FALSE;
	 if (!xdr_Date2_t (xdrs, &objp->ValidEndDate))
		 return FALSE;
	return TRUE;
}
//	如果设置9日为24连续运营，则9日购买的车票在9日、10日均可使用
//	简单地说，如果购买单程票的日期为ConsecutiveOperationDays，则单日票可延长一个日有效期
//	Date2_t                                  ConsecutiveOperationDays<>;            /* 24小时连续运营的日期集合 */
// 运营日定义为[2:00AM, 24+2:00AM)

bool_t
xdr_CCHS_Sytem_t (XDR *xdrs, CCHS_Sytem_t *objp)
{
	register int32_t *buf;

	 if (!xdr_Seconds_t (xdrs, &objp->TrafficMonitorInterval))
		 return FALSE;
	 if (!xdr_Seconds_t (xdrs, &objp->SJTOvertime))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->StaffTicketGroupDefinition.StaffTicketGroupDefinition_val, (u_int *) &objp->StaffTicketGroupDefinition.StaffTicketGroupDefinition_len, ~0,
		sizeof (StaffTicketGroupDefinition_t), (xdrproc_t) xdr_StaffTicketGroupDefinition_t))
		 return FALSE;
	 if (!xdr_SecondsSinceMidNight_t (xdrs, &objp->StartofDay))
		 return FALSE;
	return TRUE;
}
//	Seconds_t                                TimeSyncInterval;                      /* 时间同步的间隔时间，建议的时间按间隔是3600秒 */	

bool_t
xdr_LCC_System_t (XDR *xdrs, LCC_System_t *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->OperatorGroup.OperatorGroup_val, (u_int *) &objp->OperatorGroup.OperatorGroup_len, ~0,
		sizeof (OperatorGroup_t), (xdrproc_t) xdr_OperatorGroup_t))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->Operator.Operator_val, (u_int *) &objp->Operator.Operator_len, ~0,
		sizeof (OperatorList_t), (xdrproc_t) xdr_OperatorList_t))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->ACZone.ACZone_val, (u_int *) &objp->ACZone.ACZone_len, ~0,
		sizeof (ACZone_t), (xdrproc_t) xdr_ACZone_t))
		 return FALSE;
	 if (!xdr_SysTimeSync_t (xdrs, &objp->SysTimeSync))
		 return FALSE;
	 if (!xdr_Times_t (xdrs, &objp->MaxPINEntryRetries))
		 return FALSE;
	 if (!xdr_ReaderErrorConstraint_t (xdrs, &objp->ReaderErrorConstraint))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_EODParameter_t (XDR *xdrs, EODParameter_t *objp)
{
	register int32_t *buf;

	 if (!xdr_EODComponentType_t (xdrs, &objp->eodCOMType))
		 return FALSE;
	switch (objp->eodCOMType) {
	case EOD_CCHSSYSNetwork:
		 if (!xdr_CCHS_NetworkTopologyParam_t (xdrs, &objp->EODParameter_t_u.CCHS_NetworkTopologyParam))
			 return FALSE;
		break;
	case EOD_CCHSSYSCalendar:
		 if (!xdr_CCHS_CalendarParam_t (xdrs, &objp->EODParameter_t_u.CCHS_CalendarParam))
			 return FALSE;
		break;
	case EOD_CCHSSYSTicket:
		 if (!xdr_CCHS_TicketParam_t (xdrs, &objp->EODParameter_t_u.CCHS_TicketParam))
			 return FALSE;
		break;
	case EOD_CCHSSYSFare:
		 if (!xdr_CCHS_FareParam_t (xdrs, &objp->EODParameter_t_u.CCHS_FareParam))
			 return FALSE;
		break;
	case EOD_CCHSSYSTEM:
		 if (!xdr_CCHS_Sytem_t (xdrs, &objp->EODParameter_t_u.CCHS_System))
			 return FALSE;
		break;
	case EOD_CCHSAGM:
		 if (!xdr_CCHS_AGMParam_t (xdrs, &objp->EODParameter_t_u.CCHS_AGMParam))
			 return FALSE;
		break;
	case EOD_CCHSTVM:
		 if (!xdr_CCHS_TVMParam_t (xdrs, &objp->EODParameter_t_u.CCHS_TVMParam))
			 return FALSE;
		break;
	case EOD_CCHSBOM:
		 if (!xdr_CCHS_BOMParam_t (xdrs, &objp->EODParameter_t_u.CCHS_BOMParam))
			 return FALSE;
		break;
	case EOD_CCHSAVM:
		 if (!xdr_CCHS_AVMParam_t (xdrs, &objp->EODParameter_t_u.CCHS_AVMParam))
			 return FALSE;
		break;
	case EOD_LCCAGM:
		 if (!xdr_LCC_AGMParam_t (xdrs, &objp->EODParameter_t_u.LCC_AGMParam))
			 return FALSE;
		break;
	case EOD_LCCTVM:
		 if (!xdr_LCC_TVMParam_t (xdrs, &objp->EODParameter_t_u.LCC_TVMParam))
			 return FALSE;
		break;
	case EOD_LCCBOM:
		 if (!xdr_LCC_BOMParam_t (xdrs, &objp->EODParameter_t_u.LCC_BOMParam))
			 return FALSE;
		break;
	case EOD_LCCAVM:
		 if (!xdr_LCC_AVMParam_t (xdrs, &objp->EODParameter_t_u.LCC_AVMParam))
			 return FALSE;
		break;
	case EOD_LCCSYSTEM:
		 if (!xdr_LCC_System_t (xdrs, &objp->EODParameter_t_u.LCC_System))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_EODFile_t (XDR *xdrs, EODFile_t *objp)
{
	register int32_t *buf;

	 if (!xdr_EODComponentType_t (xdrs, &objp->EODComponentType))
		 return FALSE;
	 if (!xdr_SZAFCTime64_t (xdrs, &objp->FileCreationTime))
		 return FALSE;
	 if (!xdr_EODParameter_t (xdrs, &objp->EODParameter))
		 return FALSE;
	 if (!xdr_MD5_t (xdrs, &objp->MD5Value))
		 return FALSE;
	return TRUE;
}
// 文件名最长为64个字节，不足64个字节的超出部分全部填写0x00

bool_t
xdr_EODComponent_t (XDR *xdrs, EODComponent_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_EODComponentType_t (xdrs, &objp->EODComponentType))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->FileName, 64,
		sizeof (ENChar_t), (xdrproc_t) xdr_ENChar_t))
		 return FALSE;
	 if (!xdr_EODVersionID_t (xdrs, &objp->ComponentEODVersionID))
		 return FALSE;
	return TRUE;
}
//	FileHeaderTag_t                 FileHeaderTag;                                  /* 文件头的标签值 */

bool_t
xdr_EODMasterConfigFile_t (XDR *xdrs, EODMasterConfigFile_t *objp)
{
	register int32_t *buf;

	 if (!xdr_EODVersionID_t (xdrs, &objp->MCNFVersionID))
		 return FALSE;
	 if (!xdr_SZAFCTime64_t (xdrs, &objp->FileCreationTime))
		 return FALSE;
	 if (!xdr_SZAFCTime64_t (xdrs, &objp->MCNFEffectiveDateTime))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->EODComponents.EODComponents_val, (u_int *) &objp->EODComponents.EODComponents_len, ~0,
		sizeof (EODComponent_t), (xdrproc_t) xdr_EODComponent_t))
		 return FALSE;
	 if (!xdr_MD5_t (xdrs, &objp->MD5Value))
		 return FALSE;
	return TRUE;
}
// ---------------------------------------------------------------------------------------
// ---- Blacklist file definition
// ---------------------------------------------------------------------------------------

bool_t
xdr_MetroBlacklistEntry_t (XDR *xdrs, MetroBlacklistEntry_t *objp)
{
	register int32_t *buf;

	 if (!xdr_TicketLogicalID_t (xdrs, &objp->TicketLogicalID))
		 return FALSE;
	 if (!xdr_BLKActionType_t (xdrs, &objp->BLKActionType))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MetroBlacklistRange_t (XDR *xdrs, MetroBlacklistRange_t *objp)
{
	register int32_t *buf;

	 if (!xdr_TicketLogicalID_t (xdrs, &objp->StartTicketLogicalID))
		 return FALSE;
	 if (!xdr_TicketLogicalID_t (xdrs, &objp->EndTicketLogicalID))
		 return FALSE;
	 if (!xdr_BLKActionType_t (xdrs, &objp->BLKActionType))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MetroFullBlacklist_t (XDR *xdrs, MetroFullBlacklist_t *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->MetroBlacklistEntry.MetroBlacklistEntry_val, (u_int *) &objp->MetroBlacklistEntry.MetroBlacklistEntry_len, ~0,
		sizeof (MetroBlacklistEntry_t), (xdrproc_t) xdr_MetroBlacklistEntry_t))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->MetroBlacklistRange.MetroBlacklistRange_val, (u_int *) &objp->MetroBlacklistRange.MetroBlacklistRange_len, ~0,
		sizeof (MetroBlacklistRange_t), (xdrproc_t) xdr_MetroBlacklistRange_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MetroIncrBlacklist_t (XDR *xdrs, MetroIncrBlacklist_t *objp)
{
	register int32_t *buf;

	 if (!xdr_TicketLogicalID_t (xdrs, &objp->TicketLogicalID))
		 return FALSE;
	 if (!xdr_IncrBlacklistType_t (xdrs, &objp->IncrBlacklistType))
		 return FALSE;
	 if (!xdr_BLKActionType_t (xdrs, &objp->BLKActionType))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_YKTBlacklistEntry_t (XDR *xdrs, YKTBlacklistEntry_t *objp)
{
	register int32_t *buf;

	 if (!xdr_YKTTicketAPPID_t (xdrs, &objp->YKTTicketAPPID))
		 return FALSE;
	 if (!xdr_BLKActionType_t (xdrs, &objp->BLKActionType))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_YKTFullBlacklist_t (XDR *xdrs, YKTFullBlacklist_t *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->YKTBlacklistEntry.YKTBlacklistEntry_val, (u_int *) &objp->YKTBlacklistEntry.YKTBlacklistEntry_len, ~0,
		sizeof (YKTBlacklistEntry_t), (xdrproc_t) xdr_YKTBlacklistEntry_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_YKTIncrBlacklist_t (XDR *xdrs, YKTIncrBlacklist_t *objp)
{
	register int32_t *buf;

	 if (!xdr_YKTTicketAPPID_t (xdrs, &objp->YKTTicketAPPID))
		 return FALSE;
	 if (!xdr_IncrBlacklistType_t (xdrs, &objp->IncrBlacklistType))
		 return FALSE;
	 if (!xdr_BLKActionType_t (xdrs, &objp->BLKActionType))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_BLKParameter_t (XDR *xdrs, BLKParameter_t *objp)
{
	register int32_t *buf;

	 if (!xdr_BLKComponentType_t (xdrs, &objp->blacklistComponentType_t))
		 return FALSE;
	switch (objp->blacklistComponentType_t) {
	case BLK_YKT_FULL:
		 if (!xdr_YKTFullBlacklist_t (xdrs, &objp->BLKParameter_t_u.YKTFullYKTBlacklist))
			 return FALSE;
		break;
	case BLK_YKT_INCR:
		 if (!xdr_array (xdrs, (char **)&objp->BLKParameter_t_u.YKTIncrYKTBlacklist.YKTIncrYKTBlacklist_val, (u_int *) &objp->BLKParameter_t_u.YKTIncrYKTBlacklist.YKTIncrYKTBlacklist_len, ~0,
			sizeof (YKTIncrBlacklist_t), (xdrproc_t) xdr_YKTIncrBlacklist_t))
			 return FALSE;
		break;
	case BLK_CCHS_FULL:
		 if (!xdr_MetroFullBlacklist_t (xdrs, &objp->BLKParameter_t_u.MetroFullCCHSBlacklist))
			 return FALSE;
		break;
	case BLK_CCHS_INCR:
		 if (!xdr_array (xdrs, (char **)&objp->BLKParameter_t_u.MetroIncrCCHSBlacklist.MetroIncrCCHSBlacklist_val, (u_int *) &objp->BLKParameter_t_u.MetroIncrCCHSBlacklist.MetroIncrCCHSBlacklist_len, ~0,
			sizeof (MetroIncrBlacklist_t), (xdrproc_t) xdr_MetroIncrBlacklist_t))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_BLKFile_t (XDR *xdrs, BLKFile_t *objp)
{
	register int32_t *buf;

	 if (!xdr_BLKComponentType_t (xdrs, &objp->BLKComponentType))
		 return FALSE;
	 if (!xdr_SZAFCTime64_t (xdrs, &objp->FileCreationTime))
		 return FALSE;
	 if (!xdr_BLKParameter_t (xdrs, &objp->BLKParameter))
		 return FALSE;
	 if (!xdr_MD5_t (xdrs, &objp->MD5Value))
		 return FALSE;
	return TRUE;
}
// 文件名最长为64个字节，不足64个字节的超出部分全部填写0x00		

bool_t
xdr_BLKComponent_t (XDR *xdrs, BLKComponent_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_BLKComponentType_t (xdrs, &objp->BLKComponentType))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->FileName, 64,
		sizeof (ENChar_t), (xdrproc_t) xdr_ENChar_t))
		 return FALSE;
	 if (!xdr_BLKVersionID_t (xdrs, &objp->BLKCOMVersionID))
		 return FALSE;
	return TRUE;
}
//	FileHeaderTag_t                 FileHeaderTag;                                  /* 文件头的标签值 */

bool_t
xdr_BLKMasterConfigFile_t (XDR *xdrs, BLKMasterConfigFile_t *objp)
{
	register int32_t *buf;

	 if (!xdr_BLKVersionID_t (xdrs, &objp->BLKMainVersionID))
		 return FALSE;
	 if (!xdr_SZAFCTime64_t (xdrs, &objp->FileCreationTime))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->BLKComponents.BLKComponents_val, (u_int *) &objp->BLKComponents.BLKComponents_len, ~0,
		sizeof (BLKComponent_t), (xdrproc_t) xdr_BLKComponent_t))
		 return FALSE;
	 if (!xdr_MD5_t (xdrs, &objp->MD5Value))
		 return FALSE;
	return TRUE;
}
// ---------------------------------------------------------------------------------------
// ---- WaiverDate file definition
// ---------------------------------------------------------------------------------------

bool_t
xdr_StationModeInfo_t (XDR *xdrs, StationModeInfo_t *objp)
{
	register int32_t *buf;

	 if (!xdr_LineID_t (xdrs, &objp->LineID))
		 return FALSE;
	 if (!xdr_StationID_t (xdrs, &objp->StationID))
		 return FALSE;
	 if (!xdr_ModeCode_t (xdrs, &objp->ModeCode))
		 return FALSE;
	 if (!xdr_SZAFCTime64_t (xdrs, &objp->ModeStartDateTime))
		 return FALSE;
	 if (!xdr_SZAFCTime64_t (xdrs, &objp->ModeEndDateTime))
		 return FALSE;
	return TRUE;
}
//struct WaiverDate_t {                                                               /*--- 模式履历类型 ---*/
//	U32_t                           WaiverDateID;                                   /* 模式履历编号 */
//	StationModeInfo_t               StationModeInfo<>;                              /* 车站模式履历 */
//};
//	FileHeaderTag_t                 FileHeaderTag;                                 /* 文件头的标签值 */

bool_t
xdr_WaiverDateMasterConfigFile_t (XDR *xdrs, WaiverDateMasterConfigFile_t *objp)
{
	register int32_t *buf;

	 if (!xdr_SZAFCTime64_t (xdrs, &objp->FileCreationTime))
		 return FALSE;
	 if (!xdr_WaiverDateVersionID_t (xdrs, &objp->WaiverDateVersionID))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->StationModeInfo.StationModeInfo_val, (u_int *) &objp->StationModeInfo.StationModeInfo_len, ~0,
		sizeof (StationModeInfo_t), (xdrproc_t) xdr_StationModeInfo_t))
		 return FALSE;
	 if (!xdr_MD5_t (xdrs, &objp->MD5Value))
		 return FALSE;
	return TRUE;
}
//#endif
/************ End of file ********************************************************/
