/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _XDREOD_H_RPCGEN
#define _XDREOD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

/*************************************************************************************************************

   苏州市轨道交通线网AFC技术规程

   Title       : xdrEOD.h
   @Version    : 2.0.0
   @author     : 宁哲
   @date       : 2010/09/26
   Description : 定义系统的设备生成文件及参数文件格式
**************************************************************************************************************/
/*               EVOLUTIONS :
**************************************************************************************************************
*  Date        *  Author              * Changes
*---------------------------------------------------------------------------------
* 2010/01/07   *  宁哲                * 1.0.0 生成文档
* 2010/01/07   *  宁哲                * 1.0.1 完善文档内容
* 2010/01/14   *  宁哲                * 1.0.2 增加LCC_System_t结构
*                                       为所有的多媒体文件增加MD5校验码。XDR文件末尾自带MD5码用于文件完整性校验。
*                                       增加 DiskQuo_t、ReaderErrorConstraint_t、BanknoteAcceptorParm_t CoinModuleParam_t、IntrusionTimeoutAfterDoorOpen
*                                       增加KeyVersionID、PassengerParam_t、MultiRideParam_t
* 2010/02/01   *  宁哲                * 1.0.3 增加对CPU储值票的相关支持
* 2010/03/02   *  宁哲                * 1.0.5 增加票务处理相关字段
* 2010/04/20   *  宁哲                * 1.0.6 合并车站信息Ext结构
*                                       EODFile_t改为单EODParameter，即每个EOD文件只能放置一个EODParameter结构
*                                       增加MD5校验码
*                                       更新EOD主控文件格式
*                                       将操作员权限列表从清分中心数据Move到线路
*                                       优化TVM乘客界面参数
* 2010/04/20   *  宁哲                * 1.0.7 增加一卡通黑名单
* 2010/05/08   *  宁哲                * 1.0.8 调整罚款参数
* 2010/05/11   *  宁哲                * 1.0.9 格式内容调整
* 2010/07/08   *  宁哲                * 1.0.12  Line_t加到CCHS_NetworkTopologyParam_t中
*                                               删除MultiRideParam_t结构体
*                                               增加换乘车站TransferStationList
*                                               将PassengerParam改为PassengerParam<>
*                                               增加EntryAtSaleStation
*                                               取消TimeSyncInterval、PanaramaPic、PanaramaSelBtn_t、MultiRideParam_t
*                                               取消SectionTypeID、PassengerParam_t
* 2010/09/26   *  宁哲                * 1.0.14 修改CCHS_Sytem_t的定义
*                                               将TVMExpressIssueFare_t改为ExpressIssueFare_t，并移至CCHS_FareParam_t
* 2010/12/8   *  诸仕荣                * 2.0.5 修改CCHS_Sytem_t的“24小时连续运营的日期”为“单程当日延长时间”
*                                               在LCC_BOMParam_t中增加“单个文件交易最大数量”
*                                               修改MetroBlacklistEntry_t、MetroBlacklistRange_t、MetroIncrBlacklist_t的物理卡号为逻辑卡号
* 2010/12/21   *  诸仕荣                * 2.0.6 修改WaiverDateMasterConfigFile_t结构，去掉WaiverDate_t结构
* 2010/2/11    *  徐志君                * 2.0.7 修改StationModeInfo_t结构，增加降级模式结束时间 
---------------------------------------------------------------------------------*/
#ifndef XDREOD_H
#define XDREOD_H

#include "xdrBaseType.h"
// ---------------------------------------------------------------------------------------
// ---- EOD file definition
// ---------------------------------------------------------------------------------------
// 线路中文名称最长为32个Unicode字符，不足32个Unicode的超出部分全部填写0x0000
// 线路英文名称最长为128个字符，不足128个字节的超出部分全部填写0x00
// 启用标志位：0: 未启用；1: 启用

struct Line_t {
	LineID_t LineID;
	CNChar_t LineCNName[32];
	ENChar_t LineENName[128];
	Boolean_t EnableFlag;
};
typedef struct Line_t Line_t;
// 车站代码
// 车站中文名称最长为32个Unicode字符，不足32个Unicode的超出部分全部填写0x0000
// 车站英文名称最长为128个字符，不足128个字节的超出部分全部填写0x00
// 车站所在线路编号
// 启用标志位：0: 未启用；1: 启用

struct Station_t {
	StationID_t StationID;
	CNChar_t StationCNName[32];
	ENChar_t StationENName[128];
	LineID_t LineID;
	Boolean_t EnableFlag;
};
typedef struct Station_t Station_t;
//	ZoneTypeID_t                             ZoneTypeID;                            /* 区域类别代码 */
// 区域中文名称最长为128个Unicode字符，不足128个Unicode的超出部分全部填写0x0000		
// 区域英文名称最长为128个字符，不足128个字节的超出部分全部填写0x00		
// 启用标志位：0: 未启用；1: 启用

struct Zone_t {
	ZoneID_t ZoneID;
	struct {
		u_int StationID_len;
		StationID_t *StationID_val;
	} StationID;
	CNChar_t ZoneCNName[128];
	ENChar_t ZoneENName[128];
	Boolean_t EnableFlag;
};
typedef struct Zone_t Zone_t;
//	SectionTypeID_t                          SectionTypeID;                         /* 区段类别代码，用于与TicketDefinition_t绑定 */
// 区段中文名称最长为32个Unicode字符，不足32个Unicode的超出部分全部填写0x0000		
// 区段英文名称最长为128个字符，不足128个字符的超出部分全部填写0x00		
// 启用标志位：0: 未启用；1: 启用

struct Section_t {
	SectionID_t SectionID;
	StationID_t StationID1;
	StationID_t StationID2;
	CNChar_t SectionCNName[32];
	ENChar_t SectionENName[128];
	Boolean_t EnableFlag;
};
typedef struct Section_t Section_t;
// 换乘车站用于判断单程票是否在购票车站进站

struct TransferStation_t {
	TransferStationID_t TransferStationID;
	struct {
		u_int StationID_len;
		StationID_t *StationID_val;
	} StationID;
};
typedef struct TransferStation_t TransferStation_t;

struct CCHS_NetworkTopologyParam_t {
	struct {
		u_int Line_len;
		Line_t *Line_val;
	} Line;
	struct {
		u_int Station_len;
		Station_t *Station_val;
	} Station;
	struct {
		u_int Zone_len;
		Zone_t *Zone_val;
	} Zone;
	struct {
		u_int Section_len;
		Section_t *Section_val;
	} Section;
	struct {
		u_int TransferStation_len;
		TransferStation_t *TransferStation_val;
	} TransferStation;
};
typedef struct CCHS_NetworkTopologyParam_t CCHS_NetworkTopologyParam_t;
//struct PassengerParam_t{
//	PassengerTypeID_t                        PassengerTypeID;                       /* 乘客类别编码 */
// 乘客类别中文名称最长为16个Unicode字符，不足16个Unicode的超出部分全部填写0x0000
//	CNChar_t                                 PassengerTypeCNName[16];               /* 乘客类别中文名称 */
// 乘客类别英文名称最长为32个字符，不足32个字节的超出部分全部填写0x00
//	ENChar_t                                 PassengerTypeENName[32];               /* 乘客类型英文简称 */	
//};
//struct MultiRideParam_t{
//	MultiRideTypeID_t                        MultiRideTypeID;                       /* 计次票乘客次数类别 */
//	MultiRideNumber_t                        MultiRideNumber;                       /* 计次票乘客次数 */      	
//};
// 车票中文名称最长为16个Unicode字符，不足16个Unicode的超出部分全部填写0x0000
// 车票英文名称最长为32个字符，不足32个字节的超出部分全部填写0x00
//	PassengerTypeID_t                        PassengerTypeID;                       /* 乘客类别，仅用于BOM界面选择，与票价无关 */
// 0: 无使用范围限制
// 1: 在限定的区域使用 
// 2: 在限定的区段使用
//	ZoneID_t                                 ZoneID;                                /* 区域类别编号 */	
//	SectionTypeID_t                          SectionTypeID;                         /* 区段类别编号 */	
//	MultiRideTypeID_t                        MultiRideTypeID;                       /* 计次类型 */	
// 0: 非纪念票; 1: 纪念票
// 0: 非记名票; 1: 记名票
// 0: 不可充值；1: 可充值
//	FareTier_t                               MaxFareTier;                           /* 最大的里程数 */
//	Boolean_t                                ExtendAuthorized;                      /* 是否允许延期 */
// 0:不优惠; 1: 联乘优惠
// 0: 未启用；1:启用

struct TicketDefinition_t {
	TicketType_t TicketType;
	CNChar_t TicketTypeCNName[16];
	ENChar_t TicketTypeENName[32];
	TicketFamily_t TicketFamily;
	AreaTicketFlag_t AreaTicketFlag;
	MultiRideNumber_t MultiRideNumber;
	ValueCent_t SaleFixedPrice;
	Boolean_t SouvenirFlag;
	Boolean_t MemberTicketFlag;
	SoundDisplayID_t SoundDisplayID;
	ConcessionalLampID_t ConcessionalLampID;
	Boolean_t AddValueAuthorized;
	ValueCent_t MinAddValue;
	ValueCent_t MaxRemainingValue;
	ValueCent_t MinEntryAmount;
	ValueCent_t MinExitAmount;
	ValueCent_t DepositValue;
	ValueCent_t DepreciationValue;
	Boolean_t RefundAuthorized;
	ValueCent_t MaxImmediateRefundAmount;
	ValueCent_t RefundCharge;
	MultiRideNumber_t MaxRideNumber;
	DurationMode_t DurationMode;
	Duration_t Duration;
	Date2_t FixedEndDate;
	Seconds_t PeriodofFreeAdjustForNoExit;
	ValueCent_t OverstayingFeeValue;
	ValueCent_t NoExitFeeValue;
	ValueCent_t SurchargeStationMisMatch;
	ConcessionType_t ConcessionType;
	Boolean_t EnableFlag;
};
typedef struct TicketDefinition_t TicketDefinition_t;
// 提示音文件名最长为8个字符，不足8个字符的超出部分全部填写0x00		

struct SoundDisplay_t {
	SoundDisplayID_t SoundDisplayID;
	ENChar_t SoundDisplayFileName[8];
	MD5_t SoundDisplayFileMD5;
};
typedef struct SoundDisplay_t SoundDisplay_t;

struct ChipDefinition_t {
	ChipType_t ChipType;
	Duration_t PhycialValidityPeriod;
	U32_t MaxChipIONumber;
};
typedef struct ChipDefinition_t ChipDefinition_t;
//	PassengerParam_t                         PassengerParam<>;                      /* 乘客类型定义 */

struct CCHS_TicketParam_t {
	struct {
		u_int ChipDefinition_len;
		ChipDefinition_t *ChipDefinition_val;
	} ChipDefinition;
	struct {
		u_int TicketDefinition_len;
		TicketDefinition_t *TicketDefinition_val;
	} TicketDefinition;
	KeyVersionID_t KeyVersionID;
};
typedef struct CCHS_TicketParam_t CCHS_TicketParam_t;

struct BankAddingValuePara_t {
	ValueCent_t BankCardPaymentMinAmount;
	ValueCent_t BankCardPaymentMaxAmount;
};
typedef struct BankAddingValuePara_t BankAddingValuePara_t;

struct TimeInterval_t {
	TimeIntervalID_t TimeIntervalID;
	SecondsSinceMidNight_t TimeIntervalValue;
};
typedef struct TimeInterval_t TimeInterval_t;

struct FareGroup_t {
	TicketFareTypeID_t TicketFareTypeID;
	DateTypeID_t DateTypeID;
	TimeIntervalID_t TimeIntervalID;
	FareGroupID_t FareGroupID;
};
typedef struct FareGroup_t FareGroup_t;

struct BaseFare_t {
	FareGroupID_t FareGroupID;
	FareTier_t FareTier;
	ValueCent_t FareAmount;
};
typedef struct BaseFare_t BaseFare_t;

struct TicketFareType_t {
	TicketType_t TicketType;
	SP_t ServiceProvider;
	TicketFareTypeID_t TicketFareTypeID;
};
typedef struct TicketFareType_t TicketFareType_t;

struct FareTierTimeTable_t {
	FareTier_t FareTier;
	Seconds_t AllowedTravelPeriod;
};
typedef struct FareTierTimeTable_t FareTierTimeTable_t;

struct FareTierMatrix_t {
	FareTier_t FareTier;
	StationID_t StationID1;
	StationID_t StationID2;
};
typedef struct FareTierMatrix_t FareTierMatrix_t;

struct ExpressIssueFare_t {
	ValueCent_t FareAmount;
	FareTier_t FareTier;
};
typedef struct ExpressIssueFare_t ExpressIssueFare_t;
// 专用于TVM金额快速购票

struct CCHS_FareParam_t {
	BankAddingValuePara_t BankAddingValuePara;
	struct {
		u_int FareGroup_len;
		FareGroup_t *FareGroup_val;
	} FareGroup;
	struct {
		u_int FareTierMatrixData_len;
		FareTierMatrix_t *FareTierMatrixData_val;
	} FareTierMatrixData;
	struct {
		u_int BaseFare_len;
		BaseFare_t *BaseFare_val;
	} BaseFare;
	struct {
		u_int TicketFareType_len;
		TicketFareType_t *TicketFareType_val;
	} TicketFareType;
	struct {
		u_int ExpressIssueFare_len;
		ExpressIssueFare_t *ExpressIssueFare_val;
	} ExpressIssueFare;
};
typedef struct CCHS_FareParam_t CCHS_FareParam_t;

struct SpecialDate_t {
	Date2_t SpecialDate;
	DateTypeID_t DateTypeID;
};
typedef struct SpecialDate_t SpecialDate_t;

struct CCHS_CalendarParam_t {
	struct {
		u_int SpecialDate_len;
		SpecialDate_t *SpecialDate_val;
	} SpecialDate;
	struct {
		u_int TimeInterval_len;
		TimeInterval_t *TimeInterval_val;
	} TimeInterval;
	struct {
		u_int FareTierTimeTable_len;
		FareTierTimeTable_t *FareTierTimeTable_val;
	} FareTierTimeTable;
};
typedef struct CCHS_CalendarParam_t CCHS_CalendarParam_t;

struct ConcessionalLampType_t {
	ConcessionalLampID_t ConcessionalLampID;
	LampColorTypeID_t LampColorTypeID;
	FrequencyWithinMin_t Frequency;
	Seconds_t DisplayPeriod;
};
typedef struct ConcessionalLampType_t ConcessionalLampType_t;
// AGM提示音列表
// AGM显示灯列表

struct CCHS_AGMParam_t {
	struct {
		u_int SoundDisplay_len;
		SoundDisplay_t *SoundDisplay_val;
	} SoundDisplay;
	struct {
		u_int ConcessionalLampType_len;
		ConcessionalLampType_t *ConcessionalLampType_val;
	} ConcessionalLampType;
	Boolean_t EntryAtSaleStation;
};
typedef struct CCHS_AGMParam_t CCHS_AGMParam_t;

struct CCHS_AVMParam_t {
	ValueCent_t MaxAddingValueAmount;
	ValueCent_t AddingValueAmountConstraint;
};
typedef struct CCHS_AVMParam_t CCHS_AVMParam_t;

struct UploadParam_t {
	Seconds_t YKTUDUploadInterval;
	Seconds_t CCHSUDUploadInterval;
	Seconds_t CCHSFINUploadInterval;
	Seconds_t CCHSARUploadInterval;
	Seconds_t CCHSEVTUploadInterval;
};
typedef struct UploadParam_t UploadParam_t;

struct DiskQuo_t {
	Percentage_t DiskAlmostFullLimit;
	Percentage_t DiskFullLimit;
};
typedef struct DiskQuo_t DiskQuo_t;

struct ReaderErrorConstraint_t {
	Times_t MetroIOMaxConsecutiveError;
	Times_t YKTIOMaxConsecutiveError;
	Times_t CashCardIOMaxConsecutiveError;
};
typedef struct ReaderErrorConstraint_t ReaderErrorConstraint_t;
//	ReaderErrorConstraint_t                  ReaderErrorConstraint;                 /* 读写器读写控制信息 */

struct LCC_AGMParam_t {
	TransactionNb_t MaxUDAmount;
	Duration_t TxnValidityDays;
	UploadParam_t AGMUploadParam;
	DiskQuo_t DiskQuo;
	TicketQuantity_t CSTStockAlmostFullLimit;
	TicketQuantity_t CSTStockAlreadyFullLimit;
};
typedef struct LCC_AGMParam_t LCC_AGMParam_t;
//struct ScreenSize_t {                                                               /*--- 屏幕尺寸类型 ---*/
//	CoordinateUnit_t                         ScreenWidth;                           /* 屏幕宽度 */
//	CoordinateUnit_t                         ScreenHeight;                          /* 屏幕高度 */
//};

struct CaptionDispay_t {
	CoordinateUnit_t DateCaptionX;
	CoordinateUnit_t DateCaptionY;
	CoordinateUnit_t DateCaptionWidth;
	CoordinateUnit_t DateCaptionHeight;
};
typedef struct CaptionDispay_t CaptionDispay_t;

struct ExpressBtn_t {
	ExpressBtnIndex_t ExpressBtnIndex;
	ValueCent_t ExpressBtnValue;
	CaptionDispay_t ExpressBtn;
	Boolean_t ExpressBtn_tEnable;
};
typedef struct ExpressBtn_t ExpressBtn_t;
//struct PanaramaPic_t {                                                              /*--- 路网全景图片 ---*/
// 路网全景中文图片文件名最长为16个Unicode字符，不足16个字节的超出部分全部填写0x00		
//	ENChar_t                                 PanaramaCNPicName[16];                 /* 路网全景中文图片文件名 */
//	MD5_t                                    PanaramaCNPicMD5;                      /* 路网全景中文图片文件整个文件二进制内容的MD5码 */
// 路网全景英文图片文件名最长为16个字节，不足16个字节的超出部分全部填写0x00		
//	ENChar_t                                 PanaramaENPicName[16];                 /* 路网全景英文图片文件名 */
//	MD5_t                                    PanaramaENPicMD5;                      /* 路网全景英文图片文件整个文件二进制内容的MD5码 */
//	CaptionDispay_t                          PanaramaPicDisplay;                    /* 路网图片显示坐标信息 */
//};
// 线路区域中文图片名最长为16个Unicode字符，不足16个字节的超出部分全部填写0x00		
// 线路区域英文图片名最长为16个字节，不足16个字节的超出部分全部填写0x00

struct LineZoneSelBtn_t {
	LineZoneSelBtnID_t LineZoneSelBtnID;
	CaptionDispay_t LineZoneSelBtnDisplay;
	Boolean_t LineZoneSelBtnEnableFlag;
	ENChar_t LineZoneCNPicName[16];
	MD5_t LineZoneCNPicMD5;
	ENChar_t LineZoneENPicName[16];
	MD5_t LineZoneENPicMD5;
	CaptionDispay_t LineZonePicDisplay;
};
typedef struct LineZoneSelBtn_t LineZoneSelBtn_t;

struct StationSelBtn_t {
	StationID_t StationID;
	LineZoneSelBtnID_t LineZoneSelBtnID;
	CaptionDispay_t StationSelBtnDisplay;
	Boolean_t StationSelBtnEnable;
};
typedef struct StationSelBtn_t StationSelBtn_t;
//	ScreenSize_t                             ScreenSize;                            /* 屏幕尺寸参数 */
//	PanaramaPic_t                            PanaramaPic;                           /* 路网全景图片(首页)类型 */
//	CaptionDispay_t                          PanaramaSelBtn_t;                      /* 路网全景图片(首页)选择按钮 */

struct TVMLineStationPic_t {
	struct {
		u_int ExpressBtn_len;
		ExpressBtn_t *ExpressBtn_val;
	} ExpressBtn;
	CaptionDispay_t DateCaptionDispay;
	CaptionDispay_t TimeCaptionDispay;
	CaptionDispay_t LocalStation;
	struct {
		u_int LineZoneSelBtn_len;
		LineZoneSelBtn_t *LineZoneSelBtn_val;
	} LineZoneSelBtn;
	struct {
		u_int StationSelBtn_len;
		StationSelBtn_t *StationSelBtn_val;
	} StationSelBtn;
};
typedef struct TVMLineStationPic_t TVMLineStationPic_t;

struct CCHS_TVMParam_t {
	TVMLineStationPic_t TVMLineStationPic;
};
typedef struct CCHS_TVMParam_t CCHS_TVMParam_t;
// 广告多媒体播放文件名最长为16个字符，不足16个字节的超出部分全部填写0x00		

struct ADItem_t {
	ADItemID_t ADItemID;
	ENChar_t ADItemFileName[16];
	MD5_t ADItemFileMD5;
	MultiMediaType_t MultiMediaType;
};
typedef struct ADItem_t ADItem_t;
// 找零器报警数量 
// 找零器停止找零数量 
// 硬币接受报警数量
// 硬币接受上限数量
// TVM可接受的硬币种类：50表示5角；100表示1元；

struct CoinModuleParam_t {
	CoinQuantity_t HopperAlmostEmptyLimit;
	CoinQuantity_t HopperEmptyLimit;
	CoinQuantity_t CoinBoxAlmostFullLimit;
	CoinQuantity_t CoinBoxFullLimit;
	struct {
		u_int AcceptableCoinValue_len;
		ValueCent_t *AcceptableCoinValue_val;
	} AcceptableCoinValue;
};
typedef struct CoinModuleParam_t CoinModuleParam_t;
// 纸币接受报警数量
// 纸币接受上限数量 	
// TVM可接受的纸币种类：100表示1元；200表示2元；以此类推

struct BanknoteAcceptorParm_t {
	BanknoteQuantity_t BankNoteBoxAlmostFullLimit;
	BanknoteQuantity_t BankNoteBoxFullLimit;
	struct {
		u_int AcceptableBankNoteValue_len;
		ValueCent_t *AcceptableBankNoteValue_val;
	} AcceptableBankNoteValue;
};
typedef struct BanknoteAcceptorParm_t BanknoteAcceptorParm_t;
// 单个文件最大交易数量
// 交易在本地保存的有效天数
// TVM数据上传参数	
// 硬盘容量控制上限	
// 读写器读写控制信息
//	ReaderErrorConstraint_t                  ReaderErrorConstraint;                 
// 纸币接收器参数
// 纸币模块参数
// 是否支持使用储值票付款 
// 最大硬币找零金额
// 最大纸币找零金额 
// 单程票不足报警数量 
// 进入到广告模式的等待时间
// 广告信息
// 广告播放方式 
// 打开维护门后，判定闯入发生的时间段
// 温度上限
// 判定温度过高越界时，设备是否自动关机
// 打印机出现故障时，设备是否继续正常工作，或是转入暂停服务

struct LCC_TVMParam_t {
	TransactionNb_t MaxUDAmount;
	Duration_t TxnValidityDays;
	UploadParam_t TVMUploadParam;
	DiskQuo_t DiskQuo;
	BanknoteAcceptorParm_t BanknoteAcceptorParm;
	CoinModuleParam_t CoinModuleParam;
	Boolean_t PaymentMeans;
	ValueCent_t MaxNbOfCoinChangeOut;
	ValueCent_t MaxNbOfBanknoteChangeOut;
	TicketQuantity_t CSTStockAlmostEmptyLimit;
	Seconds_t TimeoutBeforeADLoad;
	struct {
		u_int ADItem_len;
		ADItem_t *ADItem_val;
	} ADItem;
	U8_t ADPlayMeans;
	Seconds_t IntrusionTimeoutBeforeLogon;
	Centidegree_t TemperatureMaxLimitation;
	Boolean_t AutomaticSwitchOff;
	Boolean_t bOutOfServicePrintError;
};
typedef struct LCC_TVMParam_t LCC_TVMParam_t;
//struct BOMOperatorAuth_t{
//	ValueCent_t                              AuthorizationMaxValue;                 /* 授权最大金额 */	
//	ValueCent_t                              PerShiftMaxAddValue;                   /* 单班最大充值额度 */	
//};
// BOM直连CCHS通讯服务器的通讯信息
// CCHS通讯IP地址，最长为16字节，不足16个字节的超出部分全部填写0x00		
// CCHS通讯IP地址
// CCHS通讯TCP Server port

struct CCHSCommunicationSrv_t {
	ENChar_t CCHSIPAddress[20];
	TCPPort_t CCHSTCPPort;
};
typedef struct CCHSCommunicationSrv_t CCHSCommunicationSrv_t;
// 自动转入退出时间 
// CCHSCommunicationSrv[0]: BOM认证服务
// CCHSCommunicationSrv[1]: 票卡充值密钥计算服务
// CCHSCommunicationSrv[2]: 票卡信息查询服务
// 其余的通讯信息暂作预留

struct CCHS_BOMParam_t {
	TransactionNb_t MaxUDAmount;
	Duration_t TxnValidityDays;
	Seconds_t NoOperatorActionTimeOut;
	CCHSCommunicationSrv_t CCHSCommunicationSrv[6];
	Seconds_t PeriodOfFreeUpdateEntry;
	ValueCent_t PerShiftMaxAddValue;
};
typedef struct CCHS_BOMParam_t CCHS_BOMParam_t;
// 单程票不足报警数量 
// BOM数据上传参数 
// 硬盘容量控制上限
// 读写器读写控制信息 
//	ReaderErrorConstraint_t                  ReaderErrorConstraint;                 
// 打印机出现故障时，设备是否继续正常工作,或是转入暂停服务
//	Boolean_t                                bOutOfServicePrintError;	

struct LCC_BOMParam_t {
	TransactionNb_t MaxUDAmount;
	TicketQuantity_t CSTStockAlmostEmptyLimit;
	UploadParam_t BOMUploadParam;
	DiskQuo_t DiskQuo;
};
typedef struct LCC_BOMParam_t LCC_BOMParam_t;
// BOM数据上传参数 
// 硬盘容量控制上限
// 读写器读写控制信息
//	ReaderErrorConstraint_t                  ReaderErrorConstraint;                 

struct LCC_AVMParam_t {
	UploadParam_t AVMUploadParam;
	DiskQuo_t DiskQuo;
};
typedef struct LCC_AVMParam_t LCC_AVMParam_t;

struct SysTimeSync_t {
	Seconds_t TimeDeviationPeriod;
	Seconds_t MinTimeDeviation;
	Seconds_t MaxTimeDeviation;
};
typedef struct SysTimeSync_t SysTimeSync_t;

struct OperatorGroup_t {
	OperatorGroupID_t OperatorGroupID;
	struct {
		u_int EQPFuncID_len;
		EQPFuncID_t *EQPFuncID_val;
	} EQPFuncID;
};
typedef struct OperatorGroup_t OperatorGroup_t;

struct ACZone_t {
	ACZoneID_t ACZoneID;
	struct {
		u_int ACZoneStationList_len;
		StationID_t *ACZoneStationList_val;
	} ACZoneStationList;
};
typedef struct ACZone_t ACZone_t;

struct OperatorList_t {
	OperatorID_t OperatorID;
	OperatorGroupID_t OperatorGroupID;
	Date2_t ValidStartDate;
	Date2_t ValidEndDate;
	ENChar_t Password[8];
	ACZoneID_t ACZoneID;
};
typedef struct OperatorList_t OperatorList_t;

struct StaffTicketGroupDefinition_t {
	StaffGroupID_t StaffGroupID;
	Date2_t ValidStartDate;
	Date2_t ValidEndDate;
};
typedef struct StaffTicketGroupDefinition_t StaffTicketGroupDefinition_t;
//	如果设置9日为24连续运营，则9日购买的车票在9日、10日均可使用
//	简单地说，如果购买单程票的日期为ConsecutiveOperationDays，则单日票可延长一个日有效期
//	Date2_t                                  ConsecutiveOperationDays<>;            /* 24小时连续运营的日期集合 */
// 运营日定义为[2:00AM, 24+2:00AM)

struct CCHS_Sytem_t {
	Seconds_t TrafficMonitorInterval;
	Seconds_t SJTOvertime;
	struct {
		u_int StaffTicketGroupDefinition_len;
		StaffTicketGroupDefinition_t *StaffTicketGroupDefinition_val;
	} StaffTicketGroupDefinition;
	SecondsSinceMidNight_t StartofDay;
};
typedef struct CCHS_Sytem_t CCHS_Sytem_t;
//	Seconds_t                                TimeSyncInterval;                      /* 时间同步的间隔时间，建议的时间按间隔是3600秒 */	

struct LCC_System_t {
	struct {
		u_int OperatorGroup_len;
		OperatorGroup_t *OperatorGroup_val;
	} OperatorGroup;
	struct {
		u_int Operator_len;
		OperatorList_t *Operator_val;
	} Operator;
	struct {
		u_int ACZone_len;
		ACZone_t *ACZone_val;
	} ACZone;
	SysTimeSync_t SysTimeSync;
	Times_t MaxPINEntryRetries;
	ReaderErrorConstraint_t ReaderErrorConstraint;
};
typedef struct LCC_System_t LCC_System_t;

struct EODParameter_t {
	EODComponentType_t eodCOMType;
	union {
		CCHS_NetworkTopologyParam_t CCHS_NetworkTopologyParam;
		CCHS_CalendarParam_t CCHS_CalendarParam;
		CCHS_TicketParam_t CCHS_TicketParam;
		CCHS_FareParam_t CCHS_FareParam;
		CCHS_Sytem_t CCHS_System;
		CCHS_AGMParam_t CCHS_AGMParam;
		CCHS_TVMParam_t CCHS_TVMParam;
		CCHS_BOMParam_t CCHS_BOMParam;
		CCHS_AVMParam_t CCHS_AVMParam;
		LCC_AGMParam_t LCC_AGMParam;
		LCC_TVMParam_t LCC_TVMParam;
		LCC_BOMParam_t LCC_BOMParam;
		LCC_AVMParam_t LCC_AVMParam;
		LCC_System_t LCC_System;
	} EODParameter_t_u;
};
typedef struct EODParameter_t EODParameter_t;

struct EODFile_t {
	EODComponentType_t EODComponentType;
	SZAFCTime64_t FileCreationTime;
	EODParameter_t EODParameter;
	MD5_t MD5Value;
};
typedef struct EODFile_t EODFile_t;
// 文件名最长为64个字节，不足64个字节的超出部分全部填写0x00

struct EODComponent_t {
	EODComponentType_t EODComponentType;
	ENChar_t FileName[64];
	EODVersionID_t ComponentEODVersionID;
};
typedef struct EODComponent_t EODComponent_t;
//	FileHeaderTag_t                 FileHeaderTag;                                  /* 文件头的标签值 */

struct EODMasterConfigFile_t {
	EODVersionID_t MCNFVersionID;
	SZAFCTime64_t FileCreationTime;
	SZAFCTime64_t MCNFEffectiveDateTime;
	struct {
		u_int EODComponents_len;
		EODComponent_t *EODComponents_val;
	} EODComponents;
	MD5_t MD5Value;
};
typedef struct EODMasterConfigFile_t EODMasterConfigFile_t;
// ---------------------------------------------------------------------------------------
// ---- Blacklist file definition
// ---------------------------------------------------------------------------------------

struct MetroBlacklistEntry_t {
	TicketLogicalID_t TicketLogicalID;
	BLKActionType_t BLKActionType;
};
typedef struct MetroBlacklistEntry_t MetroBlacklistEntry_t;

struct MetroBlacklistRange_t {
	TicketLogicalID_t StartTicketLogicalID;
	TicketLogicalID_t EndTicketLogicalID;
	BLKActionType_t BLKActionType;
};
typedef struct MetroBlacklistRange_t MetroBlacklistRange_t;

struct MetroFullBlacklist_t {
	struct {
		u_int MetroBlacklistEntry_len;
		MetroBlacklistEntry_t *MetroBlacklistEntry_val;
	} MetroBlacklistEntry;
	struct {
		u_int MetroBlacklistRange_len;
		MetroBlacklistRange_t *MetroBlacklistRange_val;
	} MetroBlacklistRange;
};
typedef struct MetroFullBlacklist_t MetroFullBlacklist_t;

struct MetroIncrBlacklist_t {
	TicketLogicalID_t TicketLogicalID;
	IncrBlacklistType_t IncrBlacklistType;
	BLKActionType_t BLKActionType;
};
typedef struct MetroIncrBlacklist_t MetroIncrBlacklist_t;

struct YKTBlacklistEntry_t {
	YKTTicketAPPID_t YKTTicketAPPID;
	BLKActionType_t BLKActionType;
};
typedef struct YKTBlacklistEntry_t YKTBlacklistEntry_t;

struct YKTFullBlacklist_t {
	struct {
		u_int YKTBlacklistEntry_len;
		YKTBlacklistEntry_t *YKTBlacklistEntry_val;
	} YKTBlacklistEntry;
};
typedef struct YKTFullBlacklist_t YKTFullBlacklist_t;

struct YKTIncrBlacklist_t {
	YKTTicketAPPID_t YKTTicketAPPID;
	IncrBlacklistType_t IncrBlacklistType;
	BLKActionType_t BLKActionType;
};
typedef struct YKTIncrBlacklist_t YKTIncrBlacklist_t;

struct BLKParameter_t {
	BLKComponentType_t blacklistComponentType_t;
	union {
		YKTFullBlacklist_t YKTFullYKTBlacklist;
		struct {
			u_int YKTIncrYKTBlacklist_len;
			YKTIncrBlacklist_t *YKTIncrYKTBlacklist_val;
		} YKTIncrYKTBlacklist;
		MetroFullBlacklist_t MetroFullCCHSBlacklist;
		struct {
			u_int MetroIncrCCHSBlacklist_len;
			MetroIncrBlacklist_t *MetroIncrCCHSBlacklist_val;
		} MetroIncrCCHSBlacklist;
	} BLKParameter_t_u;
};
typedef struct BLKParameter_t BLKParameter_t;

struct BLKFile_t {
	BLKComponentType_t BLKComponentType;
	SZAFCTime64_t FileCreationTime;
	BLKParameter_t BLKParameter;
	MD5_t MD5Value;
};
typedef struct BLKFile_t BLKFile_t;
// 文件名最长为64个字节，不足64个字节的超出部分全部填写0x00		

struct BLKComponent_t {
	BLKComponentType_t BLKComponentType;
	ENChar_t FileName[64];
	BLKVersionID_t BLKCOMVersionID;
};
typedef struct BLKComponent_t BLKComponent_t;
//	FileHeaderTag_t                 FileHeaderTag;                                  /* 文件头的标签值 */

struct BLKMasterConfigFile_t {
	BLKVersionID_t BLKMainVersionID;
	SZAFCTime64_t FileCreationTime;
	struct {
		u_int BLKComponents_len;
		BLKComponent_t *BLKComponents_val;
	} BLKComponents;
	MD5_t MD5Value;
};
typedef struct BLKMasterConfigFile_t BLKMasterConfigFile_t;
// ---------------------------------------------------------------------------------------
// ---- WaiverDate file definition
// ---------------------------------------------------------------------------------------

struct StationModeInfo_t {
	LineID_t LineID;
	StationID_t StationID;
	ModeCode_t ModeCode;
	SZAFCTime64_t ModeStartDateTime;
	SZAFCTime64_t ModeEndDateTime;
};
typedef struct StationModeInfo_t StationModeInfo_t;
//struct WaiverDate_t {                                                               /*--- 模式履历类型 ---*/
//	U32_t                           WaiverDateID;                                   /* 模式履历编号 */
//	StationModeInfo_t               StationModeInfo<>;                              /* 车站模式履历 */
//};
//	FileHeaderTag_t                 FileHeaderTag;                                 /* 文件头的标签值 */

struct WaiverDateMasterConfigFile_t {
	SZAFCTime64_t FileCreationTime;
	WaiverDateVersionID_t WaiverDateVersionID;
	struct {
		u_int StationModeInfo_len;
		StationModeInfo_t *StationModeInfo_val;
	} StationModeInfo;
	MD5_t MD5Value;
};
typedef struct WaiverDateMasterConfigFile_t WaiverDateMasterConfigFile_t;
#endif
/************ End of file ********************************************************/

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Line_t (XDR *, Line_t*);
extern  bool_t xdr_Station_t (XDR *, Station_t*);
extern  bool_t xdr_Zone_t (XDR *, Zone_t*);
extern  bool_t xdr_Section_t (XDR *, Section_t*);
extern  bool_t xdr_TransferStation_t (XDR *, TransferStation_t*);
extern  bool_t xdr_CCHS_NetworkTopologyParam_t (XDR *, CCHS_NetworkTopologyParam_t*);
extern  bool_t xdr_TicketDefinition_t (XDR *, TicketDefinition_t*);
extern  bool_t xdr_SoundDisplay_t (XDR *, SoundDisplay_t*);
extern  bool_t xdr_ChipDefinition_t (XDR *, ChipDefinition_t*);
extern  bool_t xdr_CCHS_TicketParam_t (XDR *, CCHS_TicketParam_t*);
extern  bool_t xdr_BankAddingValuePara_t (XDR *, BankAddingValuePara_t*);
extern  bool_t xdr_TimeInterval_t (XDR *, TimeInterval_t*);
extern  bool_t xdr_FareGroup_t (XDR *, FareGroup_t*);
extern  bool_t xdr_BaseFare_t (XDR *, BaseFare_t*);
extern  bool_t xdr_TicketFareType_t (XDR *, TicketFareType_t*);
extern  bool_t xdr_FareTierTimeTable_t (XDR *, FareTierTimeTable_t*);
extern  bool_t xdr_FareTierMatrix_t (XDR *, FareTierMatrix_t*);
extern  bool_t xdr_ExpressIssueFare_t (XDR *, ExpressIssueFare_t*);
extern  bool_t xdr_CCHS_FareParam_t (XDR *, CCHS_FareParam_t*);
extern  bool_t xdr_SpecialDate_t (XDR *, SpecialDate_t*);
extern  bool_t xdr_CCHS_CalendarParam_t (XDR *, CCHS_CalendarParam_t*);
extern  bool_t xdr_ConcessionalLampType_t (XDR *, ConcessionalLampType_t*);
extern  bool_t xdr_CCHS_AGMParam_t (XDR *, CCHS_AGMParam_t*);
extern  bool_t xdr_CCHS_AVMParam_t (XDR *, CCHS_AVMParam_t*);
extern  bool_t xdr_UploadParam_t (XDR *, UploadParam_t*);
extern  bool_t xdr_DiskQuo_t (XDR *, DiskQuo_t*);
extern  bool_t xdr_ReaderErrorConstraint_t (XDR *, ReaderErrorConstraint_t*);
extern  bool_t xdr_LCC_AGMParam_t (XDR *, LCC_AGMParam_t*);
extern  bool_t xdr_CaptionDispay_t (XDR *, CaptionDispay_t*);
extern  bool_t xdr_ExpressBtn_t (XDR *, ExpressBtn_t*);
extern  bool_t xdr_LineZoneSelBtn_t (XDR *, LineZoneSelBtn_t*);
extern  bool_t xdr_StationSelBtn_t (XDR *, StationSelBtn_t*);
extern  bool_t xdr_TVMLineStationPic_t (XDR *, TVMLineStationPic_t*);
extern  bool_t xdr_CCHS_TVMParam_t (XDR *, CCHS_TVMParam_t*);
extern  bool_t xdr_ADItem_t (XDR *, ADItem_t*);
extern  bool_t xdr_CoinModuleParam_t (XDR *, CoinModuleParam_t*);
extern  bool_t xdr_BanknoteAcceptorParm_t (XDR *, BanknoteAcceptorParm_t*);
extern  bool_t xdr_LCC_TVMParam_t (XDR *, LCC_TVMParam_t*);
extern  bool_t xdr_CCHSCommunicationSrv_t (XDR *, CCHSCommunicationSrv_t*);
extern  bool_t xdr_CCHS_BOMParam_t (XDR *, CCHS_BOMParam_t*);
extern  bool_t xdr_LCC_BOMParam_t (XDR *, LCC_BOMParam_t*);
extern  bool_t xdr_LCC_AVMParam_t (XDR *, LCC_AVMParam_t*);
extern  bool_t xdr_SysTimeSync_t (XDR *, SysTimeSync_t*);
extern  bool_t xdr_OperatorGroup_t (XDR *, OperatorGroup_t*);
extern  bool_t xdr_ACZone_t (XDR *, ACZone_t*);
extern  bool_t xdr_OperatorList_t (XDR *, OperatorList_t*);
extern  bool_t xdr_StaffTicketGroupDefinition_t (XDR *, StaffTicketGroupDefinition_t*);
extern  bool_t xdr_CCHS_Sytem_t (XDR *, CCHS_Sytem_t*);
extern  bool_t xdr_LCC_System_t (XDR *, LCC_System_t*);
extern  bool_t xdr_EODParameter_t (XDR *, EODParameter_t*);
extern  bool_t xdr_EODFile_t (XDR *, EODFile_t*);
extern  bool_t xdr_EODComponent_t (XDR *, EODComponent_t*);
extern  bool_t xdr_EODMasterConfigFile_t (XDR *, EODMasterConfigFile_t*);
extern  bool_t xdr_MetroBlacklistEntry_t (XDR *, MetroBlacklistEntry_t*);
extern  bool_t xdr_MetroBlacklistRange_t (XDR *, MetroBlacklistRange_t*);
extern  bool_t xdr_MetroFullBlacklist_t (XDR *, MetroFullBlacklist_t*);
extern  bool_t xdr_MetroIncrBlacklist_t (XDR *, MetroIncrBlacklist_t*);
extern  bool_t xdr_YKTBlacklistEntry_t (XDR *, YKTBlacklistEntry_t*);
extern  bool_t xdr_YKTFullBlacklist_t (XDR *, YKTFullBlacklist_t*);
extern  bool_t xdr_YKTIncrBlacklist_t (XDR *, YKTIncrBlacklist_t*);
extern  bool_t xdr_BLKParameter_t (XDR *, BLKParameter_t*);
extern  bool_t xdr_BLKFile_t (XDR *, BLKFile_t*);
extern  bool_t xdr_BLKComponent_t (XDR *, BLKComponent_t*);
extern  bool_t xdr_BLKMasterConfigFile_t (XDR *, BLKMasterConfigFile_t*);
extern  bool_t xdr_StationModeInfo_t (XDR *, StationModeInfo_t*);
extern  bool_t xdr_WaiverDateMasterConfigFile_t (XDR *, WaiverDateMasterConfigFile_t*);

#else /* K&R C */
extern bool_t xdr_Line_t ();
extern bool_t xdr_Station_t ();
extern bool_t xdr_Zone_t ();
extern bool_t xdr_Section_t ();
extern bool_t xdr_TransferStation_t ();
extern bool_t xdr_CCHS_NetworkTopologyParam_t ();
extern bool_t xdr_TicketDefinition_t ();
extern bool_t xdr_SoundDisplay_t ();
extern bool_t xdr_ChipDefinition_t ();
extern bool_t xdr_CCHS_TicketParam_t ();
extern bool_t xdr_BankAddingValuePara_t ();
extern bool_t xdr_TimeInterval_t ();
extern bool_t xdr_FareGroup_t ();
extern bool_t xdr_BaseFare_t ();
extern bool_t xdr_TicketFareType_t ();
extern bool_t xdr_FareTierTimeTable_t ();
extern bool_t xdr_FareTierMatrix_t ();
extern bool_t xdr_ExpressIssueFare_t ();
extern bool_t xdr_CCHS_FareParam_t ();
extern bool_t xdr_SpecialDate_t ();
extern bool_t xdr_CCHS_CalendarParam_t ();
extern bool_t xdr_ConcessionalLampType_t ();
extern bool_t xdr_CCHS_AGMParam_t ();
extern bool_t xdr_CCHS_AVMParam_t ();
extern bool_t xdr_UploadParam_t ();
extern bool_t xdr_DiskQuo_t ();
extern bool_t xdr_ReaderErrorConstraint_t ();
extern bool_t xdr_LCC_AGMParam_t ();
extern bool_t xdr_CaptionDispay_t ();
extern bool_t xdr_ExpressBtn_t ();
extern bool_t xdr_LineZoneSelBtn_t ();
extern bool_t xdr_StationSelBtn_t ();
extern bool_t xdr_TVMLineStationPic_t ();
extern bool_t xdr_CCHS_TVMParam_t ();
extern bool_t xdr_ADItem_t ();
extern bool_t xdr_CoinModuleParam_t ();
extern bool_t xdr_BanknoteAcceptorParm_t ();
extern bool_t xdr_LCC_TVMParam_t ();
extern bool_t xdr_CCHSCommunicationSrv_t ();
extern bool_t xdr_CCHS_BOMParam_t ();
extern bool_t xdr_LCC_BOMParam_t ();
extern bool_t xdr_LCC_AVMParam_t ();
extern bool_t xdr_SysTimeSync_t ();
extern bool_t xdr_OperatorGroup_t ();
extern bool_t xdr_ACZone_t ();
extern bool_t xdr_OperatorList_t ();
extern bool_t xdr_StaffTicketGroupDefinition_t ();
extern bool_t xdr_CCHS_Sytem_t ();
extern bool_t xdr_LCC_System_t ();
extern bool_t xdr_EODParameter_t ();
extern bool_t xdr_EODFile_t ();
extern bool_t xdr_EODComponent_t ();
extern bool_t xdr_EODMasterConfigFile_t ();
extern bool_t xdr_MetroBlacklistEntry_t ();
extern bool_t xdr_MetroBlacklistRange_t ();
extern bool_t xdr_MetroFullBlacklist_t ();
extern bool_t xdr_MetroIncrBlacklist_t ();
extern bool_t xdr_YKTBlacklistEntry_t ();
extern bool_t xdr_YKTFullBlacklist_t ();
extern bool_t xdr_YKTIncrBlacklist_t ();
extern bool_t xdr_BLKParameter_t ();
extern bool_t xdr_BLKFile_t ();
extern bool_t xdr_BLKComponent_t ();
extern bool_t xdr_BLKMasterConfigFile_t ();
extern bool_t xdr_StationModeInfo_t ();
extern bool_t xdr_WaiverDateMasterConfigFile_t ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_XDREOD_H_RPCGEN */
