CC=arm-linux-gcc
#DEG=-DDEFINE_SUZHOU_XIAN=1


1:liblinux4418_493.Test.so
liblinux4418_493.Test.so: global.o 
	$(CC)  -shared -o liblinux4418_493.Test.so global.o


global.o:global.c 
	$(CC) -c $(DEG) global.c -o global.o -fPIC

clean:
	rm -f *.o liblinux4418_493.so